### ISSUE TITLE
Hide charts

### ISSUE THREAD

**Issue by justweb1** [home-assistant/home-assistant-polymer#100]
Please add the ability to hide the chart view on the more info dialogs. This could be done through the `customize:` component in the configuration.yaml.

```
customize:
  sensor.anything:
    friendly_name: "Something"
    icon: mdi:transparent
    hideChart: true
```
