### ISSUE TITLE
[lovelace] Picture Entity state_image doesn't override camera_image

### ISSUE THREAD

**Issue by Djebouh** [home-assistant/home-assistant-polymer#1467]
**Home Assistant release with the issue:**
0.73.2

**Description of problem:**
I have a picture entity with a defined camera_image and also a state_image.
When the entity is in the state associated to a state_image, the image displayed is still the one from the camera.

Here is my object:
```
          - type: picture-entity
            entity: group.presence
            state_image:
              "home": http://farm7.static.flickr.com/6220/6220100616_a877f41a66_b.jpg
            camera_image: camera.xiaofang

```

**Additional information:**
The use case is to not display the camera but a fixed image when we are at home.
