### ISSUE TITLE
FR: Entities and Entity-Filter card shows more info for media players

### ISSUE THREAD

**Issue by JesseWebDotCom** [home-assistant/home-assistant-polymer#1544]
When using the entities or entity-filter cards, media players only show "state" - ex. "playing".  Ideally they would show info like what's playing (ex. media_title, media_library_name, media_series_title, etc).

Here's an example where the only info shown besides icon and name is state (i.e. playing):
```
  - type: entity-filter
      show_empty: false
      entities:
        - entity: media_player.office_atv
          name: Apple TV
      state_filter:
        - 'playing'
```
