### ISSUE TITLE
Lovelace: Custom UI error

### ISSUE THREAD

**Issue by cdce8p** [home-assistant/home-assistant-polymer#1651]
**Home Assistant release with the issue:** 0.78.0.dev0
**Home Assistant Frontend version:** 20180903.0

**Last working Home Assistant release (if known):** -

**Browser and Operating System:**
- Ubuntu 18.04 LTS
- Firefox, Chrome

**Description of problem:**
Custom ui for entities within lovelace (#1404) doesn't seem to work.
 It only shows the error below shortly, before it disappears.
However the entity won't be displayed afterwards.
It appears that others might have similar issues: https://community.home-assistant.io/t/lovelace-custom-ui/65026
![bildschirmfoto vom 2018-09-10 14-25-00](https://user-images.githubusercontent.com/30130371/45297354-6217f000-b505-11e8-83ad-7b1730bb34a5.png)

I've run the following in the `web console` to check if the `customElement` is defined:
```
customElements.get('number-lovelace')
```
The result was:
```
class NumberLovelace extends StateCardInputNumber {

}
```

**Javascript errors shown in the web inspector (if applicable):**
```
```

**Additional information:**
`ui-lovelace.yaml`
```yaml
resources:
  - url: /local/number-lovelace.js
    type: js

views:
  - title: Test
    cards:
      - type: entities
        entities:
          - entity: input_number.test
            type: "custom:number-lovelace"
```

`www/number-lovelace.js`
```js
var StateCardInputNumber = customElements.get('state-card-input_number')

class NumberLovelace extends StateCardInputNumber {  }
customElements.define('number-lovelace', NumberLovelace);
```
