### ISSUE TITLE
Lovelace Weather card displays wrong units

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/home-assistant-polymer#1679]
**Home Assistant release with the issue:**
0.75

**Description of problem:**
The Lovelace weather card displays the weather as if the units are metric, when some are metric and some are imperial.

It should be possible to specify the units (imperial/metric) on a per source basis.

For example, define the units as metric in `homeassistant`, and define the following:

```yaml
weather:
- platform: darksky
  api_key: !secret darksky_api_key
  units: uk2
```

This is then shows the wind in km/h, when the figure is actually MPH. This is apparent if you also configure the darksky sensor also using `uk2`, where the wind sensor has the units specified as MPH.
