### ISSUE TITLE
Style 'border-radius' does not work on image element after upgrade to 0.80.3

### ISSUE THREAD

**Issue by azuwis** [home-assistant/home-assistant-polymer#1810]
**Home Assistant release with the issue:** 0.80.3 (frontent 201810180)

**Last working Home Assistant release (if known):** 0.80.1 (frontent 201810140)

**Browser and Operating System:**

- Google Chrome on Android 8.1
- Firefox 62 on Debian Linux
- Chromium 70 on Debian Linux

**Description of problem:**

After upgrade HomeAssistant from 0.80.1 to 0.80.3, `border-radius` style does apply anymore.
Using the following config, get squre image on all browser mentioned above.
```
- type: picture-elements
  image: /local/floorplan.png
  elements:
    - type: image
      entity: device_tracker.owntracks_1
      image: /local/device_1.jpg
      state_filter:
        not_home: grayscale(100%)
      style:
        top: 85%
        left: 95%
        width: 5%
        border-radius: 50%
```

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
