### ISSUE TITLE
Header toggle doesn't work on groups

### ISSUE THREAD

**Issue by Fusseldieb** [home-assistant/home-assistant-polymer#1819]
In Home Assistant (in 0.80.3 - but also earlier versions too) when I switch a whole card on, the light domains switch, but the group domains don't. That means that when I switch the whole card on, groups are leaved untouched and therefore some things aren't turned on.

Other bug is that group domains don't light up (turn yellow) when they're turned on, only lights. That leads to a odd appearance on the UI.

I made a GIF to show what I mean:

![groupsbug](https://user-images.githubusercontent.com/4715129/47260824-d2b51380-d498-11e8-91f1-cfa89f304fd6.gif)

**Comment by iantrich** [comment]
@Fusseldieb what is the configuration for this?

**Comment by Fusseldieb** [comment]
@iantrich 
```
      - id: 814ba0a8956f418498eaf64f0e23bb3f  # Automatically created id
        type: entities
        title: Quarto Valentino
        control: hidden
        entities:
          - entity: group.suite_valentino_quarto
            name: Quarto
            icon: mdi:bed-empty
          - entity: light.banheiro_valentino
            name: Banheiro
            icon: mdi:shower
```
_ui-lovelace.yaml_
