### ISSUE TITLE
Nested groups get repeated on more info card

### ISSUE THREAD

**Issue by tboyce1** [home-assistant/home-assistant-polymer#187]
Here is a package to recreate the issue:

```
sensor:
  - platform: template
    sensors:
      group_bug_sensor:
        value_template: "Some value"

group:
  group_bug_inner:
    name: Inner
    entities:
      - sensor.group_bug_sensor
      
  group_bug_outer:
    name: Outer
    entities:
      - group.group_bug_inner
      
  group_bug_view:
    name: Group Bug
    view: yes
    entities:
      - group.group_bug_outer
```

Going to the "Group Bug" view and clicking on the header for "Outer" shows this:

![image](https://cloud.githubusercontent.com/assets/1326315/22388741/b710fde8-e4a7-11e6-9dfb-c19c6f6bd4f9.png)

The list keeps going until eventually the page crashes.
