### ISSUE TITLE
"Show_header_toggle: no" stopped working after updating to 0.81.0

### ISSUE THREAD

**Issue by Dinth** [home-assistant/home-assistant-polymer#1873]
**Home Assistant release with the issue:**

0.81.0
**Last working Home Assistant release (if known):**

0.80.3

**Description of problem:**

After updating to 0.81.0 i found out that "show_header_toggle" option for entities glance cards doesnt work anymore: doesnt hide the switch on the top of the glance card.

![screenshot 2018-10-27 at 08 35 44](https://user-images.githubusercontent.com/313674/47601096-5acc7900-d9c3-11e8-8490-4c5733d55313.png)

**Additional information:**

Configuration:
```
- id: 50cf7a4451834091abd54ff75d527872  # Automatically created id
        type: entities
        show_header_toggle: no
        entities:
          - light.front_outside_light_level
          - .....

```
