### ISSUE TITLE
issues with sensor inside a vertical-stack

### ISSUE THREAD

**Issue by VirtualL** [home-assistant/home-assistant-polymer#1878]
**Home Assistant release with the issue:** 0.81.0 

**Last working Home Assistant release (if known):** 0.80.1 (I think it was working till 0.80.3)
Hello 

**Browser and Operating System:** MacOS with Chrome, Safari, and iOS with Safari  (Latest Version)

**Description of problem:**
Hello, I got an Error in Lovelace Cards, In some a lot of Combinations.

I think the problem made with sensor code.
this config is working:
```
    cards:
      - id: fe6c46a6d0f84761a2846e0451591d68  # Automatically created id
        type: vertical-stack
        cards:
          - type: glance
            title: מידע
            column_width: calc(100% / 3)
            entities:
              - binary_sensor.door_window_sensor_158d0000d834ac
              - vacuum.xiaomi_vacuum
              - climate.living_room

      - id: 9cfd7b3c4ea7453cb1543ad998f67274  # Automatically created id
        type: sensor
        entity: sensor.hass
```
![image](https://user-images.githubusercontent.com/10164935/47602580-9c701a80-d9e9-11e8-9fa1-5997afb012dd.png)

and this Config will not work: (just move the sensor into the vertical-stack)
```
    cards:
      - id: fe6c46a6d0f84761a2846e0451591d68  # Automatically created id
        type: vertical-stack
        cards:
          - type: glance
            title: מידע
            column_width: calc(100% / 3)
            entities:
              - binary_sensor.door_window_sensor_158d0000d834ac
              - vacuum.xiaomi_vacuum
              - climate.living_room

          - id: 9cfd7b3c4ea7453cb1543ad998f67274  # Automatically created id
            type: sensor
            entity: sensor.hass
```
<img width="468" alt="screen shot 2018-10-27 at 13 11 07" src="https://user-images.githubusercontent.com/10164935/47602598-cfb2a980-d9e9-11e8-80e9-0948d3820136.png">

**Javascript errors shown in the web inspector (if applicable):**
```
NONE
```

**Additional information:**
I believe its happening because of this marge 
https://github.com/home-assistant/home-assistant-polymer/pull/1868
