### ISSUE TITLE
0.81  Alarm Control Panel issues with armed night and code

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#1907]
**Home Assistant release with the issue:**

0.81.1
**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

Windows 10 Chrome 70 and also Android 9.0 and Chrome 70
**Description of problem:**

When I add the new alarm control panel card the Armed Night button is missing text and the code should not show up since I do not use a code in my setup.

```
  - type: alarm-panel
    entity: alarm_control_panel.home
    states:
    - arm_away
    - arm_night
```

configuration.yaml for `alarm_control_panel`

```
alarm_control_panel:
  platform: manual
  name: "Home"
  pending_time: 60
  delay_time: 60
  disarmed:
    trigger_time: 0
```
**Javascript errors shown in the web inspector (if applicable):**
```
N/A
```

**Additional information:**
![image](https://user-images.githubusercontent.com/1634145/47619406-9175c280-da9b-11e8-9eff-5e55d0e9e972.png)
