### ISSUE TITLE
Feature request: picture-elements width+height?

### ISSUE THREAD

**Issue by Sjeff** [home-assistant/home-assistant-polymer#1938]
Hi,

If this is not the right place to request any features please close or remove this issue.

Is it possible to add the card-width and card-height to the picture-elements card?
When specified the width and height the default theme background is shown instead of the image.

This way you can have a picture elements card that fits with the theme.

```
- type: picture-elements
  card-width: 750px
  card-height: 950px
  elements:
    - ...
```
instead of
```
- type: picture-elements
  image: /local/banners/empty_long_placeholder.png
  elements:
    - ...
```
