### ISSUE TITLE
0.81.2 Lovelace Thermostat card not showing up for Honeywell component

### ISSUE THREAD

**Issue by MDieperink** [home-assistant/home-assistant-polymer#1943]
**Home Assistant release with the issue:**

0.81.2

**Last working Home Assistant release (if known):**
N/A as thermostat card was introduced in 0.81

**Browser and Operating System:**

Firefox / Chrome on Windows 10

**Description of problem:**

Thermostat card not showing up for Honeywell climate component. When I add the Honeywell Climate component in an entity card it shows up as expected.

**Javascript errors shown in the web inspector (if applicable):**
```
TypeError: stateObj.attributes.operation_list is undefined
```

**Additional information:**
Configuration:
```
climate:
  - platform: honeywell
    username: !secret honeywell_username
    password: !secret honeywell_password
    scan_interval: 600
```
ui-lovelace.yaml:
```
  - title: Climate
    icon: mdi:temperature-celsius
    cards:
    # working entity card
      - type: entities
        title: Climate
        show_header_toggle: false 
        entities:
          - entity: climate.thermostat
    # not working thermostat card
      - type: thermostat
        entity: climate.thermostat
```
