### ISSUE TITLE
Lovelace media-player card not working with conditional card (Cannot read property 'states' of undefined)

### ISSUE THREAD

**Issue by jptrsn** [home-assistant/home-assistant-polymer#1945]
This is related to issue #1904, which has been closed although I am continuing to see the problematic behaviour when using a conditional card in combination with media-player card. Seeing the problem on 0.81.2 of Home Assistant.

Configuration is:
```
      # Forked-Daapd Music Server
      - type: conditional
        conditions:
          - entity: media_player.music_server
            state: "playing"
        card:
          type: media-control
          title: Media Server
          entity: media_player.music_server
```

Javascript console reports the following error:
```
8a696fdac4ce3eb749b3.chunk.js:1933 hui-conditional-card TypeError: Cannot read property 'states' of undefined
    at HTMLElement.set hass [as hass] (8a696fdac4ce3eb749b3.chunk.js:1269)
    at HTMLElement.setConfig (8a696fdac4ce3eb749b3.chunk.js:418)
    at create_card_element_createElement (8a696fdac4ce3eb749b3.chunk.js:1933)
    at createCardElement (8a696fdac4ce3eb749b3.chunk.js:1933)
    at config.cards.map.cardConfig (8a696fdac4ce3eb749b3.chunk.js:1995)
    at Array.map (<anonymous>)
    at HTMLElement._createCards (8a696fdac4ce3eb749b3.chunk.js:1995)
    at Object.runMethodEffect [as fn] (app-c039924c.js:1067)
    at runEffectsForProperty (app-c039924c.js:1067)
    at runEffects (app-c039924c.js:1067)
```

Lovelace UI renders this error message:

![2018-11-01_13-58-29](https://user-images.githubusercontent.com/5185267/47869883-775f1b80-ddde-11e8-9b16-66b3a5ec0112.png)
