### ISSUE TITLE
Lovelace 'iframe card' with option 'aspect_ratio:' does not render correct in Chrome browser

### ISSUE THREAD

**Issue by IoTmessenger** [home-assistant/home-assistant-polymer#2001]
**Home Assistant release with the issue:**

`Home Assistant 0.81.6`

**Last working Home Assistant release (if known):**

`Home Assistant 0.79.3`

**Browser and Operating System:**

```
Windows 10 Edu 64b on desktop
Windows 10 home 64b on laptop
---
Chrome Version 70.0.3538.77
Microsoft Edge 42.17134.1.0
Chome browser 70.0.3538.80 on Android 9 phone
```

**Description of problem:**

The 'iframe card' with the use of option 'aspect_ratio:' does not render correct in the above listed browsers on several computers.

Clearing browser cache or using Incognito Mode has not solved this issue.
In Firefox browser as well as the 'Home Assistant' app on my iPad the same code renders both cards OK.

Using the code beneath (added newly to my config for testing), the same as both 'Height-Width' example configs on [the HAGallery page](https://home-assistant-lovelace-gallery.netlify.com/#demo-hui-iframe-card) results in the same rendering of both cards with different values. 

```
  - title: iframe
    cards:
      - type: iframe
        url: https://embed.windy.com/embed2.html
        aspect_ratio: 50%
      - type: iframe
        url: https://embed.windy.com/embed2.html
        aspect_ratio: 100%
```

See links to screenshots of output in both Chrome (NOK) and Firefox (OK) on the same computer, using the code above:

[Chrome: NOK](https://ibb.co/g8ubHq)
[Firefox: OK](https://ibb.co/gVFoVA)

This behavior I experience since HA 0.81.x. Whatever value is being used as the percentage, no change in how the card is rendered (it looks like the first value is used for both cards).

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
