### ISSUE TITLE
Click on one history-graph opens other

### ISSUE THREAD

**Issue by bigboban** [home-assistant/home-assistant-polymer#2052]
**Home Assistant release with the issue:** 0.82.0

**Last working Home Assistant release (if known):** N/A

**Browser and Operating System:** Chrome/Windows

**Description of problem:**

First my idea - this may have some context with this issue: https://github.com/home-assistant/home-assistant-polymer/issues/2049. I think there is some "cache" because first load lasts significantly more time that 2nd and other graph opens.

![image](https://user-images.githubusercontent.com/7159224/48496208-d76bae00-e831-11e8-863c-1c8e3ee7a02f.png)

**So problem is**: I have two history-graphs as two components on lovelace-ui. When i click first component it opens first graph named "netatmo_public" with position issue mentioned in connected bug. OK. I close first graph. **Now i click second component (second row) but it opens "netatmo_public" graph again (without delay)! BUG!** I can try it many times and it always opens first graph if I click second row. Only page refresh fix this. If I do page refresh and click second row it shows correct second graph.

I think there is some "caching" and on cache-read it takes/shows incorrect graph..

**Javascript errors shown in the web inspector (if applicable):**
```
history_graph:
  netatmo_public:
    name: Netatmo public
    entities:
      - sensor.netatmo_public_data_gust_strength
      - sensor.netatmo_public_data_humidity
      - sensor.netatmo_public_data_pressure
      - sensor.netatmo_public_data_rain
      - sensor.netatmo_public_data_temperature
      - sensor.netatmo_public_data_wind_strength
    hours_to_show: 168
    refresh: 60
  vnitrni:
    name: Vnitřní čidla
    entities:
          - sensor.loznice_teplota
          - sensor.loznice_vlhkost
          - sensor.loznice_tlak
          - sensor.teplota_detsky_pokoj
          - sensor.vlhkost_detsky_pokoj
          - sensor.teplota_v_komore
          - sensor.vlhkost_v_komore
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
          - sensor.netatmo_indoor_pressure
          - sensor.netatmo_indoor_co2
          - sensor.netatmo_indoor_noise
          - sensor.teplota_akvarium
          - sensor.teplota_v_pracovne_force
          - sensor.vlhkost_v_pracovne
          - sensor.tlak_v_pracovne
    hours_to_show: 168
    refresh: 60
```

Lovelace:
```
  - id: 6  # Automatically created id
    title: Grafy
    cards:
      - type: entities
        title: Grafy
        entities:
          - history_graph.netatmo_public  
          - history_graph.vnitrni_cidla
```

**Additional information:**
```

```
