### ISSUE TITLE
panel: true does not size correctly on mobile

### ISSUE THREAD

**Issue by jaburges** [home-assistant/home-assistant-polymer#2056]
**Home Assistant release with the issue:**
0.82 
(existed with previous)

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

iOS app
chrome iOS
edge iOS
safari iOS

**Description of problem:**

in` ui-lovelace.yaml`
when `panel: true`
instead of fitting to the full screen - there is a white space about 5mm thick on the right hand side top to bottom of the specific page.

```
- title: Settings
    icon: mdi:settings
    id: settings
    panel: true
    cards:
```

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
@zsarnett has an image if needed
