### ISSUE TITLE
Configuration validation can not be trusted.

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/home-assistant-polymer#2066]
**Home Assistant release with the issue:**

0.82.1
**Last working Home Assistant release (if known):**
Unknown

**Browser and Operating System:**
Not applicable.

**Description of problem:**

![image](https://user-images.githubusercontent.com/15093472/48672592-20747880-eb38-11e8-89a1-b4f8070710ca.png)
```
hassio ha check
ERROR
INFO:homeassistant.util.package:Attempting install of colorlog==3.1.4
Testing configuration at /config
ERROR:homeassistant.util.yaml:YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 76 and 78.
```

**Additional information:**
configuration:
```
77:sensor:
78:  platform: demo
79:sensor:
80:  platform: demo
```
The UI Config check should fail on this.

**Comment by Petro31** [comment]
Hasn't this always been there?

**Comment by ludeeus** [comment]
I do believe that the button worked before

**Comment by balloob** [comment]
Well I am not sure how exactly it is called, but a duplicate key is not a fatal error but just a warning. It still results in a valid config, yet maybe not the config the user might have wanted?

**Comment by ludeeus** [comment]
Since it unvalidates my entire sensor config, this bug is bad..
```
sensor:
  - platform: ruter
    stop_id: 2190400
  - platform: versions
    name: Hass Available to Install Version
    beta: true
    source: docker
sensor:
  platform: demo
sensor:
  platform: demo
```
With this config, none of the defined sensors are set up.
