### ISSUE TITLE
Weather card does not render if initially visible

### ISSUE THREAD

**Issue by nkaminski** [home-assistant/home-assistant-polymer#2139]
**Home Assistant release with the issue:**
0.82.1

**Last working Home Assistant release (if known):**
Not known

**Browser and Operating System:**
Chrome 71.0.3578.62 on Mac OS X 10.14

**Description of problem:**
If the frontend / UI is opened such that the weather card is visible *without needing to scroll or change views* the weather card fails to render and instead shows as a small blank space (Between the front hall group and vacuum card in my screenshot). Once you navigate to another view and back, the Weather card loads as expected.

**Javascript errors shown in the web inspector (if applicable):**
none shown

**Additional information:**
<img width="799" alt="screen shot 2018-11-28 at 9 42 34 am" src="https://user-images.githubusercontent.com/2483681/49163288-5a8d0980-f2f2-11e8-958b-115981b854d9.png">

**Comment by zsarnett** [comment]
Are you sure there are no errors in your Home Assistant Log nor the Console of the Dev tools in your browser?

**Comment by nkaminski** [comment]
I didn't see anything, but I will reproduce this again and verify.

On November 30, 2018 12:19:22 PM CST, Zack Arnett <notifications@github.com> wrote:
>Are you sure there are no errors in your Home Assistant Log nor the
>Console of the Dev tools in your browser?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/home-assistant/home-assistant-polymer/issues/2139#issuecomment-443292643

-- 
Sent from my Android device with K-9 Mail.

**Comment by nkaminski** [comment]
No errors or warnings in JS console, HA log is also free of errors.

**Comment by nkaminski** [comment]
After updating to 0.84.1, this now results in the following error in the log when this occurs:

Log Details (ERROR)
Wed Dec 12 2018 20:54:10 GMT-0600 (Central Standard Time)

https://localhost/frontend_latest/bf7146608f595468a214.chunk.js:3157:1377 Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by nkaminski** [comment]
Sure, my config is quite involved so I will setup a dev instance within the next day or two and see if I can isolate what specifically triggers this and share.

In the mean time, the config for the impacted weather card (darksky) is:
```
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

```
and impacted camera card:
  ```
- platform: mjpeg
    name: Frontyard Camera
    mjpeg_url: http://videoserverpi:8080/?action=stream

```

The weather card is in the default view:
```
default_view:
   view: yes
   name: Main
   entities:
      - sun.sun
      - weather.dark_sky
      - device_tracker.devicea
      - device_tracker.deviceb
      - device_tracker.devicec
      - group.climate
      - group.recroom
      - group.livingroom
      - group.fronthall
      - binary_sensor.garage_door
      - binary_sensor.leak_sensor_1
      - binary_sensor.leak_sensor_2
      - binary_sensor.rec_room_motion
      - binary_sensor.front_hall_motion
      - vacuum.roomba
      - alert.garage_door
```
and the camera card is in another separate view:
```
holiday_decor:
   name: Holiday Decor
   view: yes
   entities:
      - camera.frontyard_camera
      - group.outdoor_holiday_decor
      - group.light_show_equipment

```

The video source of this camera is mjpg-streamer running on an RPi3. Connectivity between this Pi and and HA server is all wired as well.

Also 2 other observations regarding this:
- This appears to impact camera cards as well
- This issue is *not* seen when using the Lovelace UI
