### ISSUE TITLE
Update tap_action and hold_action configs

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2180]
We have decided that we're going to update the config to make it more explicit.

We will make it more explicit by making sure all actions and relevant data needs to be defined under the `tap_action` or `hold_action` keys.

Currently, having both tap and hold actions set to service will not work, as both are configured with service as a sibling key instead of under the `tap` or `hold` keys.

Suggested format;

```
# simple
tap_action: toggle

# advanced
tap_action:
  action: call-service
  service: light.turn_on
  data:
    entity_id: light.kitchen 
```
