### ISSUE TITLE
plant-status broken in 0.84.1

### ISSUE THREAD

**Issue by raccettura** [home-assistant/home-assistant-polymer#2301]
**Home Assistant release with the issue:**
0.84.1

**Last working Home Assistant release (if known):**
0.83.x

**Browser and Operating System:**

iOS/Mac

**Description of problem:**

Config looks like
```
      - id: 237943c64ae54d4d8768d99a3ad52116  # Automatically created id
        type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.snake_plant
          - type: plant-status
            entity: plant.fern_plant
```
plant status seems to result in JS error

**Javascript errors shown in the web inspector (if applicable):**
```
/frontend_latest/bf7146608f595468a214.chunk.js:2982:308 Uncaught TypeError: Cannot read property 'name' of undefined
```

**Additional information:**
Looks like it's:
```
computeTitle(stateObj) {
    return this.config.name || Object(_common_entity_compute_state_name__WEBPACK_IMPORTED_MODULE_4__.a)(stateObj)
}
```

**Comment by iantrich** [comment]
@raccettura remove you `id`

**Comment by talondnb** [comment]
I have the same issue here:

`/frontend_latest/bf7146608f595468a214.chunk.js:2982:308 Uncaught TypeError: Cannot read property 'name' of undefined`

My configuration.yaml section:

```
plant:
  aloe_gasteria_inner:
    sensors:
      moisture: sensor.aloe_gasteria_inner_moisture
      battery: sensor.aloe_gasteria_inner_battery
      temperature: sensor.aloe_gasteria_inner_temperature
      conductivity: sensor.aloe_gasteria_inner_conductivity
      brightness: sensor.aloe_gasteria_inner_light_intensity
    min_moisture: 10
    min_battery: 15
    # min_conductivity: 500
    # min_temperature: 15
  aloe_gasteria_outer:
    sensors:
      moisture: sensor.aloe_gasteria_outer_moisture
      battery: sensor.aloe_gasteria_outer_battery
      temperature: sensor.aloe_gasteria_outer_temperature
      conductivity: sensor.aloe_gasteria_outer_conductivity
      brightness: sensor.aloe_gasteria_outer_light_intensity
    min_moisture: 10
    min_battery: 15
    # min_conductivity: 500
    # min_temperature: 15
  outdoor_yucca:
    sensors:
      moisture: sensor.outdoor_yucca_moisture
      battery: sensor.outdoor_yucca_battery
      temperature: sensor.outdoor_yucca_temperature
      conductivity: sensor.outdoor_yucca_conductivity
      brightness: sensor.outdoor_yucca_light_intensity
    min_moisture: 10
    min_battery: 15
    # min_conductivity: 500
    # min_temperature: 15

```
groups.yaml

```
plants_tab:
  name: Plants
  icon: mdi:flower
  view: yes
  entities:
    - group.aloe_gasteria_inner
    # - plant.aloe_gasteria_inner
    - group.aloe_gasteria_outer
    # - plant.aloe_gasteria_outer
    - group.outdoor_yucca
    # - plant.outdoor_yucca

outdoor_yucca:
  name: Outdoor Yucca
  entities:
    - plant.outdoor_yucca

```
etc

Any ideas?
