### ISSUE TITLE
device_class timestamp in lovelace not working

### ISSUE THREAD

**Issue by Martinvdm** [home-assistant/home-assistant-polymer#2302]
**Home Assistant release with the issue:**

0.84

**Last working Home Assistant release (if known):**
(new function)

**Browser and Operating System:**

Docker

**Description of problem:**

Device_class format in lovelace not working for example with last_boot

**Additional information:**
#2087 
```
    cards:
       - type: entities
         show_header_toggle: false
         title: Systeem info
         entities:
               - entity: sensor.last_boot
                 format: relative
```
formatting shown as: 2018-09-27T21:06:15+02:00
