### ISSUE TITLE
Dark Sky weather card in Classic UI broken with 0.84

### ISSUE THREAD

**Issue by m0wlheld** [home-assistant/home-assistant-polymer#2310]
**Home Assistant release with the issue:**

0.84.0 to 0.84.2

**Last working Home Assistant release (if known):**
0.83.3

**Browser and Operating System:**

Firefox 64.0 on Windows 10 Professional x86_64
also Microsoft Edge 

**Description of problem:**

Defined weather component using platform 'darksky' does not render in Classic UI, when being part of a group. Renders fine with Lovelace UI. On classic UI, an error message is added to the system's log:

> 2018-12-14 16:44:07 ERROR (MainThread) [frontend.js.latest.201812110] http://host.example.com/frontend_latest/bf7146608f595468a214.chunk.js:3157:1358 TypeError: this.config is undefined

**Javascript errors shown in the web inspector (if applicable):**
```
TypeError: this.config is undefined[Weitere Informationen] bf7146608f595468a214.chunk.js:3157
	computeName bf7146608f595468a214.chunk.js:3157
	runMethodEffect app-0d042052.js:248
	_evaluateBinding app-0d042052.js:248
	runBindingEffect app-0d042052.js:248
	runEffectsForProperty app-0d042052.js:248
	runEffects app-0d042052.js:248
	_propagatePropertyChanges app-0d042052.js:248
	_propertiesChanged app-0d042052.js:248
	_flushProperties app-0d042052.js:895
	_flushProperties app-0d042052.js:248
	ready app-0d042052.js:248
	ready app-0d042052.js:232
	ready bf7146608f595468a214.chunk.js:3157
	_enableProperties app-0d042052.js:895
	connectedCallback app-0d042052.js:224
	connectedCallback app-0d042052.js:232
	dynamicContentUpdater app-0d042052.js:2637
	_updateCard bf7146608f595468a214.chunk.js:3388
	createObserver/this.observer< bf7146608f595468a214.chunk.js:3388
```

**Additional information:**

Displaying an attribute from dark sky (via template sensor) works however, just the card by itself fails.

configuration.yaml:
```
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
sensor:
  - platform: template
    sensors:
      pressure:
        value_template: "{{ states.weather.dark_sky.attributes.pressure }}"
        entity_id: weather.dark_sky
```
groups.yaml:

```
default_view:
  name: home
  view: yes
  icon: mdi:home
  entities:
    - group.environment
    - weather.dark_sky

environment:
  entities:
    - sensor.pressure
```
