### ISSUE TITLE
Lovelace Light card cannot control brightness of left card

### ISSUE THREAD

**Issue by pszafer** [home-assistant/home-assistant-polymer#2324]
Hello,

So I use horizontal / vertical-stack together with light card.
With config such as below on mobile phone I cannot change brightness of light when it is off:
![image](https://user-images.githubusercontent.com/690510/50042157-977e2d80-0060-11e9-8330-f9d3b0479e0b.png)

because it is too close to the left edge of screen. I scroll site instead.

```
cards:
  - cards:
      - entity: light.l1
        name: Balkon
        type: light
      - entity: light.l2
        name: Choinka
        type: light
    type: horizontal-stack
  - cards:
      - entity: light.yeelight
        name: Sofa lewa
        type: light
      - entity: light.yeelight2
        name: Sofa prawa
        type: light
    type: horizontal-stack
type: vertical-stack
```

Easiest way to fix I think would be add ability to click on this gauge so user don't have to slide slider.
