### ISSUE TITLE
Entity divider causes error in UI Editor, fallback to YAML editor

### ISSUE THREAD

**Issue by jensihnow** [home-assistant/home-assistant-polymer#2325]
**Home Assistant release with the issue:**

0.84.2 

**Last working Home Assistant release (if known):**

None

**Browser and Operating System:**
Firefox 63.0.3 (64-Bit) on MacOS but most likely every browser

**Description of problem:**

When using lovelace in storage mode and while editing a card the very basic divider entity is not supported causing fallback to YAML editor. Such a simple configuration should be supported by the editor as it is a rather common entity to add.

```
Your config is not supported by the UI editor:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.1.type` 
but received `"divider"`.
Falling back to YAML editor. 
```

Sample configuration:

```
entities:
  - entity: fan.xyz
  - type: divider
  - entity: sensor.xyz_aqi
show_header_toggle: false
title: ZZZ
type: entities
```

**Additional information:**

Not sure if this is a feature request or just a missing implementation of an existing feature. As it causes fallback to yaml editor (especially for people migrating) this seems to be a good enhancement if previously expected.
