### ISSUE TITLE
History-Graph not respecting conf yaml Unit System

### ISSUE THREAD

**Issue by SupahNoob** [home-assistant/home-assistant-polymer#2394]
**Home Assistant release with the issue:**
0.84.6

**Last working Home Assistant release (if known):**
n/a

**Browser and Operating System:**
n/a ... but
- Chrome 71 on Windows 7
- Chrome 71 on Android 9

**Description of problem:**
PROBLEM: temperature sensor is shown in Celsius (see below for example pics)
INTENDED BEHAVIOR: sensor is shown in units of whatever is preferred by User
QUICK FIX: use a template sensor to manually convert C -> F, then use resulting entity in History-Graph

My **assumption** is that the units are stored in-db as celsius (a more universal format), and when rendered to the user, the conversion is done. History-Graph does not perform this conversion, and simply reads directly from the database. I do not know if this applies to other conversions (meters -> feet, etc). I have not investigated to confirm/deny my assumption. : )

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Additional information:**
```yaml
# configuration.yaml

homeassistant:
  ...
  unit_system: imperial
```
```yaml
# ui-lovelace.yaml

views:
  ...
  - title: Data
    icon: mdi:poll
    cards:
      - type: history-graph
        title: Temperature
        hours_to_show: 168
        refresh_interval: 300
        entities:
          - entity: sensor.hallway_thermostat_hallway_temperature
            name: Inside
          - entity: sensor.weather_temperature
            name: Outside
```
renders as...

![image](https://user-images.githubusercontent.com/14192437/50564208-cf37d700-0ce8-11e9-9ed6-f21ea5b94cb0.png)

...with entities list showing

![image](https://user-images.githubusercontent.com/14192437/50564236-04442980-0ce9-11e9-9df6-d63c087a397e.png)

// edit1
fixed as ...

```yaml
# configuration.yaml

sensor:
  ...
  - platform: template
    sensors:
      # BUG REPORT: https://github.com/home-assistant/home-assistant-polymer/issues/2394
      # Rename C -> F for use in comparison monitoring in Lovelace UI.
      weather_temperature_bugfix_for_lovelace:
        unit_of_measurement: '°F'
        value_template: "{{ states('sensor.weather_temperature') }}"
```
```yaml
# ui-lovelace.yaml

views:
  ...
  - title: Data
    icon: mdi:poll
    cards:
      - type: history-graph
        title: Temperature
        hours_to_show: 168
        refresh_interval: 300
        entities:
          - entity: sensor.hallway_thermostat_hallway_temperature
            name: Inside
          - entity: sensor.weather_temperature_bugfix_for_lovelace
            name: Outside
```
![image](https://user-images.githubusercontent.com/14192437/50564635-11164c80-0cec-11e9-95df-f6abed0b58fd.png)
