### ISSUE TITLE
Right clicking on entity button in firefox can result in button getting smaller

### ISSUE THREAD

**Issue by Lopton** [home-assistant/home-assistant-polymer#2396]
**Home Assistant release with the issue:**
0.84.6 

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Windows 10 Firefox 64.0 (64-bit)

**Description of problem:**
I have 1 vertical stack, with 3 horizontal stacks, with 3 entity-buttons each. In Firefox, if I right click on the entity buttons the icons and buttons change size and get smaller depending on the length of the label. [Picture here ](https://imgur.com/hSZJrEL)

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
```
        - cards:
          - cards:
              - entity: light.dining_room_overhead
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.front_entry_overhead
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.garage_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
            type: horizontal-stack
          - cards:
              - entity: light.guest_bedroom_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.gym_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.kitchen_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
            type: horizontal-stack
          - cards:
              - entity: light.master_bathroom_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.master_bedroom_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.office_main_lights
                type: entity-button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
            type: horizontal-stack
        type: vertical-stack
```

**Comment by nicop4** [comment]
Hello
Same behaviour here. I use Firefox on MacOS Mojave.
The icon size also change if the state of the entity associated to the button changes in the background while the page is displayed.

```yaml
views:
  - title: Main
    id: test
    cards:
      - type: vertical-stack
        cards: 
          - type: thermostat
            entity: climate.family_room
          - type: custom:button-card
            entity: sensor.family_room_thermostat_hvac_state
            icon: mdi:radiator-off
            size: 10%
            state:
              - value: 'heating'
                icon: mdi:radiator
                color: rgb(255, 129, 0)
```

I use Home Assistant release 0.85.1, but the problem was present before. I don't know since when though.
It works fine on Safari or Chrome.

I will try to investigate on my side.
