### ISSUE TITLE
Card headlines are not displayed correctly when entity-filter is first card

### ISSUE THREAD

**Issue by klada** [home-assistant/home-assistant-polymer#2409]
If the first card in Lovelace UI is an `entity-filter` card and the filter does not match any entites, then all of the other card headings in Lovelace UI are not displayed correctly.

The headings should always be large and bold, but the empty `entity-filter` causes them to be displayed like normal text. See screenshots.

Lovelace config:

```yaml
title: Home
views:
    - title: Home
      path: home
      icon: mdi:home
      cards:
         - type: entity-filter
           show_empty: false
           entities:
              - binary_sensor.bathroom_window
              - binary_sensor.kitchen_window
           state_filter:
               - "on"
               - "open"
           card:
               title: Open Windows
         - type: entities
           title: Misc
           show_header_toggle: false
           entities:
               - sun.sun
               - sensor.yr_symbol
```

**Broken heading**:
![screenshot_20190105_155306](https://user-images.githubusercontent.com/3250940/50725735-61cde100-1102-11e9-812a-76211f3dd01f.png)

**Good headings** (`state_filter` matches):
![screenshot_20190105_155331](https://user-images.githubusercontent.com/3250940/50725744-87f38100-1102-11e9-9fa9-a4145758a3bd.png)
