### ISSUE TITLE
GEO Location Map Lovelace Card - problem on mobiles

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-polymer#2430]
**Home Assistant release with the issue:**

0.85.0b0 and also b1
**Last working Home Assistant release (if known):**
new feature in 0.85.0

**Browser and Operating System:**

All browsers on iOS - the iOS beta app and chrome
**Description of problem:**

The card displays perfectly however on a mobile device tapping on an event does not show event details like it does on Win10 Chrome:
![image](https://user-images.githubusercontent.com/36390762/50935350-dbc5e780-14bf-11e9-9e8c-45ca660e4ff6.png)

Tapping on AR should show these details but does not on a mobile device.

![image](https://user-images.githubusercontent.com/36390762/50935368-eed8b780-14bf-11e9-9fdc-30d39ee9265e.png)

```
          - type: map
            geo_location_sources:
              - nsw_rural_fire_service_feed
            entities:
              - zone.home
```
**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
