### ISSUE TITLE
Resources not saved with raw config editor

### ISSUE THREAD

**Issue by phdelodder** [home-assistant/home-assistant-polymer#2436]
**Home Assistant release with the issue:**
0.85.0

**Last working Home Assistant release (if known):**
0.84.6

**Browser and Operating System:**
Chrome/Windows 10

**Description of problem:**
I want to a add a few resources using the raw config editor. 
Steps to reproduce: 
- adding the needed resouces lines
- Click save (do notice no network connectivity is done)
- close the editor
- reopen the editor the lines are going. 

My other custom resources where also removed so my lovelace is showing all red squares. 

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

These lines I want to add: 
```
resources:
  - url: /local/custom-lovelace/button-card.js
    type: module
  - url: /local/custom-lovelace/vertical-stack-in-card.js?v=0.0.9
    type: js
```
