### ISSUE TITLE
hide default_view?

### ISSUE THREAD

**Issue by AnderssonPeter** [home-assistant/home-assistant-polymer#245]
Is there some way to hide `default_view` (HOME).

i have tried both
```
default_view:
  view: no
  control: hidden
```
and
```
homeassistant:
  customize:
    group.default_view:
      hidden: yes
```
none of them work.
