### ISSUE TITLE
Maps card does not support card level themes

### ISSUE THREAD

**Issue by lizaoreo** [home-assistant/home-assistant-polymer#2582]
**Home Assistant release with the issue:**

0.86.3

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Windows 10, Chrome (71)

**Description of problem:**

Maps card doesn't appear to support card level themes.  I set up the slate theme from the community theme share forum, but on the maps you can't see the icons for places (like home) or the center button controls very well with that theme because it has white for the primary text color.  I created a theme that just changes the primary text color to red and applied it to the map card like below.  Nothing happened.  I could apply to a glance card just above the map and that worked as expected (text color changed).  If I applied it to the page/tab, it worked as expected on everything, including the icons in the map.  It's probably just not coded to support it, but it would be very helpful for stuff like this since the map itself can't be changed to better match the theme.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
```yaml
  - type: map
    theme: default2
    entities:
      - device_tracker.me
      - zone.home
    aspect_ratio: 50%
    default_zoom: 16
```
