### ISSUE TITLE
Inconsistent display behavior between cards with same entity

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#2607]
**Home Assistant release with the issue:**

0.86.3

**Last working Home Assistant release (if known):**

n/a

**Browser and Operating System:**

MacOS 10.14, Google Chrome 71.0.3578.98 (Official Build) (64-bit)

**Description of problem:**

I've seen different display behaviors between different card types:

![2019-01-28 13 17 19](https://user-images.githubusercontent.com/195327/51836056-7bc4a300-22ff-11e9-9679-76aeb2f2e52a.gif)

Noticeable in the above recording:

- One card is not showing the current color of the entity (LED strip is set to blue), while others do.
- Some cards have a transition animation to the blue color (via purple), others don't.
- One card capatilizes entity name (none of the names have been overridden in the UI)

**Javascript errors shown in the web inspector (if applicable):** n/a

**Additional information:**

```yaml
  - cards:
      - type: glance
        entities:
          - entity: light.livingroom_bar
        show_state: true
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        entity: light.livingroom_bar
      - type: light
        entity: light.livingroom_bar
      - type: entities
        entities:
          - entity: light.livingroom_bar
```
