### ISSUE TITLE
Entity Button Card inconsistent size

### ISSUE THREAD

**Issue by tomlut** [home-assistant/home-assistant-polymer#2614]
**Home Assistant release with the issue:**

0.86.3

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Windows 10, Firefox 64.0.2, Chrome 71.0.3578.98
iOS 12.1.2, Safari and Home Assistant Helper App v 1.5.0

**Description of problem:**

When a panel is displayed containing an entity button card the card will display as a large size. Clicking once reduces the size, only then does further clicking toggle the state of the entity.

This occurs if the entity button card is in a vertical stack card, a custom stack-in card or as a stand alone card in the panel.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Card config:

```
type: entity-button
tap_action:
  action: toggle
hold_action:
  action: more-info
entity: switch.xmas_tree_lights
theme: Backend-selected
```

Before first click: https://i.imgur.com/vU3ij7D.png

After first click: https://i.imgur.com/6nHjMqP.png
