### ISSUE TITLE
Lovelace Entity Card - Remote. No toggle switch

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/home-assistant-polymer#2644]
**Home Assistant release with the issue:**
0.86.3

**Last working Home Assistant release (if known):**
Works for non-Lovelace UI. Config using groups.yaml
```
    entities:
      - remote.sharptv

```
A toggle on/off switch is provided in the card for the entity remote.sharptv.

**Browser and Operating System:**

Chrome
**Description of problem:**
Lovelace - using Entity Card for Remote entity does not provide a toggle switch with the remote entity.  It does however show the remote entity's state  as "on" or "off" where the toggle switch otherwise would be located.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**    
Using Lovelace:
```
   cards:
     - type: entities
       title: Remote Control
       show_header_toggle: false
       entities:
         - remote.sharptv 
```
