### ISSUE TITLE
entity-button not retaining name of call-service

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/home-assistant-polymer#2645]
**Home Assistant release with the issue:**

0.86.4

**Last working Home Assistant release (if known):**

N/A

**Browser and Operating System:**

WIn 10 Chrome

**Description of problem:**

I create the Button Card below and it works. However, if I edit the Card Configuration (both modes), the service line reads
```
service: ''
```

If I resave, the card no longer works. I get that it says: "Toggle Editor to input Service Data". But if saved Service Data will be stripped when re-editing, that would be good to know as well.

RAW CONFIG
```
type: entity-button
tap_action:
  action: call-service
  service: shell_command.volumio_rock
hold_action:
  action: none
entity: switch.volumio_test
icon: 'mdi:music'
name: Play Rock
```

Here are the pertinent parts of configuration.yaml
```
switch:
  platform: command_line
  switches:
    volumio_test:
      command_on: ""
      command_off: ""

shell_command:
  volumio_rock: 'curl 192.168.1.77/api/v1/commands/\?cmd\=playplaylist\&name\=Rock'

```

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

Cheers!

**Comment by iantrich** [comment]
I can replicate this. Not sure what the issue is yet

**Comment by CyrisXD** [comment]
Confirmed issue here too.

**Comment by mcaden** [comment]
Same, I'm using the following:

```
icon: 'mdi:surround-sound'
name: Whole House
hold_action:
  action: none
entity: group.speakers
type: entity-button
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: "home/speakers"
    payload_template: >
      {% if is_state('group.speakers', 'on') %}
        { "cmd": "OFF-ALL" }
      {% else %}
        { "cmd": "ON-ALL" }
      {% endif %}
```

If I save, it works as intended. If I edit the card, the config is cleared leaving only the following:

```
hold_action:
  action: none
tap_action:
  action: call-service
  service: ''
name: Whole House
type: entity-button
entity: group.speakers
icon: 'mdi:surround-sound'
```
