### ISSUE TITLE
panel_iframe has zero height

### ISSUE THREAD

**Issue by Boosik** [home-assistant/home-assistant-polymer#2683]
**Home Assistant release with the issue:**
0.86.4
Frontend JavaScript version: latest

**Last working Home Assistant release (if known):**
~0.83

**Browser and Operating System:**

Windows 10 Home 1809 17763.253
Chrome 73.0.3683.10

Works fine in Edge browser.

**Description of problem:**
iFrame panels have zero height making them invisible. When I manually edit the height then then iFrame is correctly shown.

This is chrome developer console screenshot of the iFrame element open in fullscreen window on FullHD monitor: 
![image](https://user-images.githubusercontent.com/939813/52283998-e01cdd80-2963-11e9-84c1-d6d8d0dfe7dc.png)

**Javascript errors shown in the web inspector (if applicable):**
```
no errors
```

**Additional information:**
Looks like new Chrome does not accept the CSS3 calc() for height (tested it in width and it worked fine).

**Comment by Boosik** [comment]
Created bug in Chromium. Can anybody create a demo with this issue? I have no spare RPi to do it.
https://bugs.chromium.org/p/chromium/issues/detail?id=930493

**Comment by iantrich** [comment]
what's your configuration? I can't replicate this

**Comment by Boosik** [comment]
My configuration is:

```
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://CCC.XXX.duckdns.org
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://TTT.XXX.duckdns.org
  esphomeyaml:
    title: ESPHome
    icon: mdi:chip
    url: https://EEE.XXX.duckdns.org
```

Pages are exposed as HTTPS using Caddy reverse proxy hassio addon https://github.com/korylprince/hassio-caddy/tree/master/caddy

My hassio instance is also exposed as HTTPS to the internet.

Pages alone work as I can open them directly in the browser and also Lovelace iframe panel works fine:
```
  - badges: []
    cards:
      - aspect_ratio: 54%
        type: iframe
        url: 'https://CCC.XXX.duckdns.org'
    icon: 'mdi:wrench'
    panel: true
    title: Config
```
