### ISSUE TITLE
The whole view's content disappears with entities indentation variations

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#2689]
**Home Assistant release with the issue:**
0.86.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
any

**Description of problem:**
The following config works fine, I can see all entities in the view:
```
default_view:
  name: "Alarm"
  view: true
  icon: mdi:shield-key
  entities:
  - group.rf_pirs
  - group.pirs_last_triggered_times
```
However, if I remove a tabulation before `entities` like this
```
default_view:
  name: "Alarm"
  view: true
  icon: mdi:shield-key
entities:
  - group.rf_pirs
  - group.pirs_last_triggered_times
```
the view becomes empty.
There is no error messages in log file and it passes validation.
In `configuration.yaml` I have
```
logger:
  default: warning
```
**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
