### ISSUE TITLE
type: entity-button, 'entity' mandatory, but not used

### ISSUE THREAD

**Issue by SaturnusDJ** [home-assistant/home-assistant-polymer#2715]
Running 0.87, same goes for 0.86.4.

Example from ui-lovelace.yaml:
```
          - type: entity-button
            name: Reload automations
            entity: script.ha_restart
            tap_action: 
              action: call-service
              service: automation.reload
            icon: mdi:reload
```

Entity is mandatory, so I just put in something unrelated, which is not being executed by the way. Why is it mandatory?
