### ISSUE TITLE
Loading indicator for system logs not centered

### ISSUE THREAD

**Issue by ljmerza** [home-assistant/home-assistant-polymer#2757]
**Home Assistant release with the issue:**

latest dev

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

ubuntu 10.18

**Description of problem:**

Loading indicator for system health and logs when restarting HA is not centered. According to [material design specs](https://material.io/design/components/progress-indicators.html#linear-progress-indicators) loading indicator should be centered.

![image](https://user-images.githubusercontent.com/4085765/52871879-105d3c80-3119-11e9-8199-ecd622de172b.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Looks like the css was added to center it but its not being centered

`src/panels/dev-info/system-log-card.ts`
```css
.loading-container {
        @apply --layout-vertical;
        @apply --layout-center-center;
        height: 100px;
}
```

latest version of chrome is saying invalid property for both apply rules above.
