### ISSUE TITLE
Add groups to history panel

### ISSUE THREAD

**Issue by andrey-git** [home-assistant/home-assistant-polymer#277]
Currently the history panel is extremely overloaded.
For example I have more than 10 temperature sensors and all of them are drawn on a single line graph.

I propose to add something like this to the history component config:
```
history:
  groups:
    name1:
      - entity_id1
      - entity_id2
    name2:
      - entity_id3
```
This will be exposed as `/api/history/groups` and used by the UI to *add* graphs.

WDYT?
