### ISSUE TITLE
lovelace "light group" control does not work with sub-groups

### ISSUE THREAD

**Issue by fermulator** [home-assistant/home-assistant-polymer#2773]
**Home Assistant release with the issue:**
`0.85.1`

**Last working Home Assistant release (if known):**
none

**Browser and Operating System:**
Firefox, Linux Mint 18

**Description of problem:**
Recently I just setup a group for all of my main floor lighting. In it there are lists of lights (individually) and groups.
```
all_main_lights:
    name: Main Floor Lights
    entities:
      - group.den_lights
      - group.kitchen_lights
      - light.dining_room
```

The groups look like this (one example)
```
den_lights:
    name: Back Den Lights
    entities:
      - light.den_main
      - light.den_rear
      - light.den_front
      - light.den_fireplace
```

In the default UI, these controls work.  If the user toggles the MAIN control, they can turn OFF and ON all lights.  Works.

![image](https://user-images.githubusercontent.com/6778269/52908210-354bcf80-323f-11e9-9406-84a88f2f6501.png)
![image](https://user-images.githubusercontent.com/6778269/52908212-3a108380-323f-11e9-8a32-fb8dfec30b64.png)

But in lovelace, the MAIN toggle is UNABLE to control the lights within the sub-groups.  The individual toggles work.

![image](https://user-images.githubusercontent.com/6778269/52908215-4563af00-323f-11e9-818a-80849b272b4f.png)
![image](https://user-images.githubusercontent.com/6778269/52908218-4a286300-323f-11e9-9ea8-441cec140b85.png)
![image](https://user-images.githubusercontent.com/6778269/52908220-4dbbea00-323f-11e9-9bcc-ba53261aa1d7.png)

**Comment by iantrich** [comment]
Use a light group

**Comment by fermulator** [comment]
hmm OK that could be a workaround (though we should expect "lights in a group" should work right? or .. prevent/warn the user that there is a better way)

**Comment by fermulator** [comment]
As per https://www.home-assistant.io/components/light.group/

Tried:
```
light:
    - platform: group
    name: Main Floor Lights
    entities:
      - group.den_lights
      - group.kitchen_lights
      - light.dining_room
```

But its still a bit wonky.  Also the docs aren't clear.  If you define that per above, how do I reference it in a script or sub-grouping?

The "name" has spaces vs. the "unique_id" uses underscores... hm blame https://github.com/home-assistant/home-assistant/issues/21137

**Comment by fermulator** [comment]
Bah
```

light:
    - platform: group
    name: Main Floor Lights
    entities:
      - light.back_den_lights
      - light.kitchen_lights
      - light.dining_room
```
, (after fixing all to "light groups")
fails to reload
```

```
Error loading /home/homeassistant/.homeassistant/configuration.yaml: while parsing a block collection
  in "/home/homeassistant/.homeassistant/groups.yaml", line 10, column 5
expected <block end>, but found '?'
  in "/home/homeassistant/.homeassistant/groups.yaml", line 11, column 5```
```
