### ISSUE TITLE
Entity type rows should support tap_action

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2774]
**Home Assistant release with the issue:**

0.87.1

**Description of problem:**

Lovelace entity rows do not support tap_action or hold_action according to the [docs](https://www.home-assistant.io/lovelace/entities/), I feel they should. The feature set should be consistent where it makes sense. 

Here is an example use case. This image is from my default_view showing a few key statistics, and I want to link the "Time Driving Today" row to my Cars view.

![Lovelace feature request](https://i.imgur.com/DpPoy0X.png)

Example config:
```
        - type: entities
          entities:
            - sensor.time_away_today
            - entity: sensor.time_driving_today
              name: Time Driving Today
              tap_action:
                action: navigate
                navigation_path: /lovelace/cars/
```
Instead of navigating it simply opens the more-info popup. This same code works in a glance card, but not an entities type card.
