### ISSUE TITLE
2nd row of alarm panel buttons misaligned

### ISSUE THREAD

**Issue by iantrich** [home-assistant/home-assistant-polymer#2781]
![image](https://user-images.githubusercontent.com/1287159/52929375-c4bdb500-3309-11e9-872d-5f4c122dd307.png)

**Comment by iantrich** [comment]
```css
    padding-top: 10px;
    margin-left: -4px;
```
cleans up that last button, but not sure how best to approach it dynamically

**Comment by iantrich** [comment]
It gets worse on mobile

![image](https://user-images.githubusercontent.com/1287159/52929574-9a202c00-330a-11e9-8fda-cec31536d17c.png)

**Comment by rgruyters** [comment]
As stated in issue #2994, this can be fixed by adding extra `4px` to the margin.

IS:
```css
.actions mwc-button {
    min-width: calc(var(--base-unit) * 9);
    margin: 0 4px;
}
```

SHOULD:
```css
.actions mwc-button {
    min-width: calc(var(--base-unit) * 9);
    margin: 0 4px 4px;
}
```
