### ISSUE TITLE
picture-elements' state-icon not properly aligned when using iron-icon-width and height

### ISSUE THREAD

**Issue by damyanor** [home-assistant/home-assistant-polymer#2808]
**Home Assistant release with the issue:**
0.87.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Opera/IE on Windows 7, chrome on android and potentially more

**Description of problem:**
When state-icon is used with style which changes the icon size (--iron-icon-width and --iron-icon-height), the icon is not placed as expected.  Example:
```
- image: /local/background.jpg
  type: picture-elements
  elements:
    - type: state-icon
      entity: sensor.ha_update
      style:
        '--iron-icon-width': 100px
        '--iron-icon-height': 100px
        top: 50%
        left: 50%
      tap_action: more-info
    - type: state-label
      entity: sensor.ha_update
      style:
        top: 90%
        left: 50%
```
results in:
![notok](https://user-images.githubusercontent.com/46784312/53096462-84378480-351f-11e9-84b2-75cbe13d617b.jpg)

Without --iron-icon-width and  --iron-icon-height params it is centered correctly.

Testing the same style with a static icon like `type: icon` works fine:
```
- image: /local/background.jpg
          type: picture-elements
          elements:
            - type: icon
              icon: mdi:checkbox-marked-circle-outline
              style:
                '--iron-icon-width': 100px
                '--iron-icon-height': 100px
                top: 50%
                left: 50%
              tap_action: more-info
            - type: state-label
              entity: sensor.ha_update
              style:
                top: 90%
                left: 50%
```
![ok](https://user-images.githubusercontent.com/46784312/53096453-7e41a380-351f-11e9-9bb7-10761dd1bde6.jpg)

but it is not a solution in some use cases (in my case - sensor template which changes icon depending on HA update availability, but also entities which require more complex conditions for state definition).
