### ISSUE TITLE
state_filter in picture-entity not working for sensors

### ISSUE THREAD

**Issue by Jeltel** [home-assistant/home-assistant-polymer#2809]
**Home Assistant release with the issue:**
0.87.0 and 0.87.1

**Last working Home Assistant release (if known):**
NA

**Browser and Operating System:**

Latest Firefox and fully updated Windows 10

**Description of problem:**

When using understanding code for a light or switch the picture turns gray when the light is off.
```
      - type: picture-entity
        entity: light.woonkamer
        image: /local/pictures/lamp_woonkamer.jpg
        state_filter:
          'off': grayscale(72%)
```
When using the same code with a sensor (device_tracker or wall switch sensor) it doesn't:
```
      - type: picture-entity
        entity: device_tracker.jelte_3t
        image: /local/pictures/jelte.jpg
        state_filter:
          home: grayscale(100%)
      - type: picture-entity
        entity: sensor.lamp_schakelaar_eettafel
        image: /local/pictures/leeslamp_bank.jpg
        state_filter:
          '0': grayscale(72%)
```
You may notice that there aren't any '' around home, for the device tracker. When editing the card via the UI the '' are removed by HA. Trying "" or other states (not_home or 1 in my cases) nothing changes.

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**
This issue was confirmed by petro and Mariusthvdb in this thread: https://community.home-assistant.io/t/lovelace-picture-entity-size-and-template-to-create-automatically/85608/15?u=jelte
