### ISSUE TITLE
Automation in UI Editor creating non-functional automations

### ISSUE THREAD

**Issue by jhfreeman1** [home-assistant/home-assistant-polymer#2815]
**Home Assistant release with the issue:**

0.88
**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Mac 10.14.3 and safari 12.0.3

**Description of problem:**

I used the Automation Editor to create my first attempt at an automation.  If a binary_sensor changed from off to on, I wanted a red light to turn on.  Very basic, but I could not get the automation to work.  I looked in automation.yaml to see the generated code from the editor:
```yaml
  alias: testing
  trigger:
  - entity_id: switch.sd2
    from: ‘off'
    platform: state
    to: ‘on'
  condition: []
  action:
  - data:
      color_name: Red
      entity_id: light.signal
      power: 'True'
    service: light.lifx_set_state
```

That code looked funky to my untrained eye.  So I edited the automations.yaml file to the following:
```yaml
  alias: testing
  trigger:
  - platform: state
    entity_id: binary_sensor.sd2
    from: 'off'
    to: 'on'
  action:
  - service: light.lifx_set_state
    data:
      color_name: Red
      entity_id: light.signal
      power: 'True'
```
This automation works as expected.  Not sure how I am messing up using the UI Automation Editor, but if this is an issue with the Editor, I thought you would like to know.

Off to teach myself some more about Home Assistant.  Thank everyone's hard work.

Please excuse if code not attached properly, but I tried to use <> in Safari, but it didn't appear to work properly.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
