### ISSUE TITLE
View in panel mode does not apply theme

### ISSUE THREAD

**Issue by unconfigured** [home-assistant/home-assistant-polymer#2839]
**Home Assistant release with the issue:** 0.88.0

**Browser and Operating System:** Chrome/Linux

**Description of problem:**
When creating a view with "panel: true" the view specific theme is not getting applied. When removing "panel: true" everything works as expected.

Example:
```
views:
  - title: MyView
    panel: true
    theme: dashboard
    cards:
        [ ... ]
```
