### ISSUE TITLE
Lovelace doesn't replace entity picture when icon is configured

### ISSUE THREAD

**Issue by Xaldimo** [home-assistant/home-assistant-polymer#2888]
**Home Assistant release with the issue:**
0.88.2

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Chrome+Windows10 and Opera+Debian

**Description of problem:**
When showing an entity in a entities card, and configuring a icon within the Lovelace config it still shows the entity picture instead of replacing it with the icon.

The device has a picture assigned, but the details I am showing should show a map marker, which doesn't happen.

On the Lovelace entities webpage it states:

icon
(string)(Optional)Overwrites icon or entity picture.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Known Devices configuration:
```yaml
phone_stephan:
  hide_if_away: false
  icon:
  mac: 00:00:00:00:00:00
  name: Stephan
  picture: /local/Stephan.jpg
  track: true
```

Sensor configuration:
```yaml
  - platform: places
    name: Geoloc Stephan
    devicetracker_id: device_tracker.phone_stephan
    options: zone,postal_town
    map_provider: google
    map_zoom: 15
    home_zone: zone.home
```

Card configuration:
```yaml
          cards:
          - type: entities
            entities:
            - entity: sensor.geoloc_stephan
              name: Location
              icon: mdi:map-marker
```
