### ISSUE TITLE
Safari & iOs - "Invalid Date" when showing input_date

### ISSUE THREAD

**Issue by fe-lix-** [home-assistant/home-assistant-polymer#2904]
**Home Assistant release with the issue:**
- 0.89.1

**UI (States or Lovelace UI?):**
- lovelace

**Browser and Operating System:**
- Safari 12.0.2
- iOs 12.1.4

**Description of problem:**
- `input_datetime` as shown as Invalid date in Safari & iOs. It works fine with Chrome.

**Additional information:**
Definition of the sensor:
```
  - platform: template
    sensors:
      last_motion_garage:
        friendly_name: "Last motion detected in Garage"
        value_template: '{{ states.binary_sensor.garage_motion.last_changed }}'
        device_class: timestamp
```

Update of the sensor:
```
- alias: Movement detected
  hide_entity: true
  initial_state: "on"
  trigger:
      .....
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.garage_last_motion
      time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
      date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
```

Lovelace card:
```
      - entities:
          - entity: switch.garage_light
          - entity: sensor.last_motion_garage
```

I guess the problem must be created by the way I populate the `input_datetime`, but I do not find an easier way to update it.
