### ISSUE TITLE
entity-filter card doesn't listen to show_header_toggle

### ISSUE THREAD

**Issue by iamtpage** [home-assistant/home-assistant-polymer#2918]
**Home Assistant release with the issue:**
0.89.1

**Last working Home Assistant release (if known):**
0.88?

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
HASS - Docker amd64
Client - Windows 10
Browser - Firefox 65.0.2 and MS Edge

**Description of problem:**
entity-filter card shows header toggle despite `show_header_toggle` being set to false

[Picture](https://i.imgur.com/ToPhwOt.png)

**Javascript errors shown in the web inspector (if applicable):**
```
None
```

**Additional information:**
Card config:
```
card:
  title: ERROR! Offline
  type: entities
entities:
  - device_tracker.a
  - device_tracker.b
  - device_tracker.c
  - device_tracker.d
  - device_tracker.routerlan
  - device_tracker.e
  - device_tracker.f
  - device_tracker.g
show_empty: false
show_header_toggle: false
state_filter:
  - not_home
type: entity-filter
```
