### ISSUE TITLE
Plant card name not working anymore

### ISSUE THREAD

**Issue by royduin** [home-assistant/home-assistant-polymer#2997]
**Home Assistant release with the issue:** 
0.90.1

**Last working Home Assistant release (if known):**
0.87.0

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
Plant sensor names do not override anymore with:
```
  - path: planten
    icon: mdi:flower
    title: Planten
    cards:
      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.plant_1
            name: Plant hoek
          - type: plant-status
            entity: plant.plant_2
            name: Plant achterraam
          - type: plant-status
            entity: plant.plant_3
            name: Plant voorraam
```

Previously I saw the names as added by this PR: https://github.com/home-assistant/home-assistant-polymer/pull/2130 but now I see `plant_1`, `plant_2` and `plant_3` again.
