### ISSUE TITLE
Different GUI representation of nameless entities from different domains

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#3046]
**Home Assistant release with the issue:**
0.91.0b2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
any

**Description of problem:**
If you create (without any name customisation) an automation
```
- alias: this_is_automation_entity
  trigger:
    platform: time
    at: '00:00:00'
  action:
    delay: '00:00:00'
```

 and an input_boolean 

```
this_is_input_boolean_entity:
```

and then use then in entity card, there will be difference:
![Screen Shot 2019-04-01 at 09 46 41 (2)](https://user-images.githubusercontent.com/13675855/55315415-325e1480-5464-11e9-801b-d64d79564c39.png)

It is very confusing and looks like a bug as the same approach was used when defining both entities.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
