### ISSUE TITLE
saved login token ignored when using Safari on macOS

### ISSUE THREAD

**Issue by squirtbrnr** [home-assistant/home-assistant-polymer#3054]
**Home Assistant release with the issue:**

0.90.2

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Docker on Synology DS1515+ running DSM 6.2.1-23824 Update 6
**Component/platform:**

Lovelace/Frontend

**Description of problem:**
After updating my MacBook to macOS 10.14.4 and Safari Version 12.1 (14607.1.40.1.4) the saved login is ignored and every time I load the frontend in a new window or tab it "forgets" I was previously authenticated and had saved the login.  The token appears in the list under my profile, and every time I click on the save login in the lower right corner a new token is created.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_api_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.0.0/24
        - 127.0.0.1
  auth_mfa_modules:
    - type: totp
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: !secret home_timezone
  customize: !include includes/customize.yaml
  customize_domain: !include includes/customize_domain.yaml
  customize_glob: !include includes/customize_glob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www/camera'
system_health:
lovelace:
  mode: yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
Originally reported here: https://community.home-assistant.io/t/saved-logins-and-refresh-tokens-ignored-in-safari-on-macos-10-14-4/108212

I realize this issue may be a macOS issue as the issue did not occur in previous macOS and Safari versions.  I even downgraded HA to 0.89.2 and the issue persisted, thus proving it's not directly caused by HA.  However, this should still be something HA should look at, in case the saved login functionality has changed when viewing with Safari.  Saying "use a different browser" is not a solution, rather just a temporary workaround.
