### ISSUE TITLE
picture-glance state image refresh not working correctly

### ISSUE THREAD

**Issue by mrsnyds** [home-assistant/home-assistant-polymer#3060]
**Home Assistant release with the issue:**  0.91.0

**Last working Home Assistant release (if known):**  0.90.2

**UI (States or Lovelace UI?):**  Lovelace UI

**Browser and Operating System:**

hassio, HassOS 2.10  Saw issue using Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) on a Windows 10 PC; identical behavior on Chrome for Android

**Description of problem:**

The browser does not automatically refresh the `state_image` as the state of the entities changes from on to off.  Starting with all entities "off", when one of the entities goes "on", the "on" image does not display as it should.  Turning that entity off (all entities now "off") the "on" image is displayed, when it should not.  Toggling entities on and off will then cause an immediate refresh, but the image displayed is not in synch with the state image that should be displayed.  Manually refreshing the browser will cause the correct image to display.   For reference, here is the `picture-glance` card configuration:
```
  - entities:
      - light.living_room_sue
      - light.living_room_pepe
    entity: light.living_room_lights
    state_image:
      'off': /local/room_light/liv_room_3_bw.jpg
      'on': /local/room_light/liv_room_3_color.jpg
    tap_action:
      action: navigate
      navigation_path: /lovelace/down/
    title: Living Room
    type: picture-glance
```

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by mrsnyds** [comment]
Just an update to let you know that none of the fixes in 0.91.1 had any impact.  Problem persists.   Tried creating a new picture glance, and same problem.

**Comment by iantrich** [comment]
A dev will comment on here if they look into/fix it

**Comment by mrsnyds** [comment]
Thanks for explaining.  Rather surprised that there are no other comments, as I expect this is a popular card ... unless of course others are not having the same experience

**Comment by forast3r** [comment]
Have experienced same issues, but only on some of the picture-glances that I use. For example, in a view with six cards, only three of them work randomly. I was using a group of lights for the entity, have also tried changing the group to light. Same results. The group and the light group work as expected.

**Comment by mrsnyds** [comment]
That's a good clue.  Same for me.  If the entity used for `state_image` is a group - either a light group, or a regular group - I see the problem with state image not refreshing.  In my example above,  `entity: light.living_room_lights` is a light group.  If I change the entity to a single light, then it works as expected.

**Comment by iantrich** [comment]
Have you verified that the state is changing as you expect under `/dev-state`?

**Comment by forast3r** [comment]
In my case in /dev-state the change is updated instantly

**Comment by mrsnyds** [comment]
Yes, I see instantaneous state changes in `/dev-state` for individual entities, as well as for the light groups, or other types of groups that are used as the `entity:` entry on the `type: picture-glance`, yet the `state_image` doesn't work as expected.

**Comment by BrianKarlsen** [comment]
Same problem here... Any chance that this will be fixed soon?

**Comment by caphm** [comment]
Same problem here. All light groups are affected.

**Comment by BrianKarlsen** [comment]
Does anyone know if this will be fixed soon?

**Comment by SteinMaerivoet** [comment]
Same experience

**Comment by ciaron23** [comment]
Hey guys, having the same problem here. I'm using picture-glance and state-image to show who's home and who isn't. I have to refresh the browser to update state-image, which isn't exactly ideal when using a hud. currently on 0.91.4

**Comment by caphm** [comment]
Additionally, this does not only affect state_image, but also the state_filter effect (grayscale) that's automatically applied for entities of the switch and light domains.

**Comment by cotwild** [comment]
I got the same problem with all group of lights... was working before some HA updates. Any news here? (Is anyone working on this?)

I doubt that this is the same problem... The referred case is a problem regarding default background color? This could as far as I understood be fixed by setting it manually...

**Comment by iantrich** [comment]
We don't really have many frontend devs. If you know any, ask them to help out 😄

**Comment by cotwild** [comment]
> We don't really have many frontend devs. If you know any, ask them to help out 😄

What language is used? I don't have a lot of time to join the team, but I could have a look at the code if the problem can be more or less located...

**Comment by iantrich** [comment]
JavaScript and TypeScript

**Comment by cotwild** [comment]
Sorry, don't have any experience with typescript... And I guess I won't be able to identify the causing code error, especially as this came up with some updates.

BTW: Thanks for your great work... HA has become an amazing home automation solution!

**Comment by mrsnyds** [comment]
WORK AROUND.  I sat down tonight, determined to find a work around ... and I found one.   Thought I would share this in case it might give an insight to someone who might have the skills to fix it.   

If I take my `picture-glance `card that is not working, and nest it inside a particular custom card, then the `state_image` works again, and the image changes to the "on" and "off" pictures as expected.  I only tried this with the [lovelace-card-templater](https://github.com/gadgetchnnel/lovelace-card-templater), so I don't know if nesting inside other cards will do the same trick.

Here is the config that DID NOT work:

```
entities:
  - light.living_room_sue
  - light.living_room_pepe
  - binary_sensor.wyze_motion_1
entity: light.living_room_lights
state_image:
  'off': /local/room_light/liv_room_3_bw.jpg
  'on': /local/room_light/liv_room_3_color.jpg
tap_action:
  action: toggle
title: Living Room
type: picture-glance 
```
And here is the config that DOES WORK.   Same config, just inside another custom card:

```
card:
  entities:
    - light.living_room_sue
    - light.living_room_pepe
    - light.frank_desk_lamp
    - binary_sensor.wyze_motion_1
  entity: light.living_room_lights
  state_image:
    'off': /local/room_light/liv_room_3_bw.jpg
    'on': /local/room_light/liv_room_3_color.jpg
  tap_action:
    action: navigate
    navigation_path: /lovelace/down/
  title: Lvng Rm
  type: picture-glance
entities:
  - light.living_room_lights
type: 'custom:card-templater' 
```

**Comment by cotwild** [comment]
Sadly I didn't get it working... Your link is broken and I cannot find the "lovelace-card-templater" module...
I tried it with other cards - but without any success...

**Comment by cwhits** [comment]
It appears that this only happens when using groups as the `entity` for a picture-glance card. Also, refreshing the page causes the state to be displayed correctly.

Example broken config:
```yaml
entities:
  - light.couch_lamp
  - light.front_lamp
entity: light.living_room_lights
image: /local/rooms/livingroom.png
title: Living room
type: picture-glance
```

```yaml
light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.couch_lamp
      - light.front_lamp
```

initial state: group off -> grayscale
switch group to on -> color
switch group to off -> color
switch group to on -> grayscale
refresh page -> color

**Comment by cwhits** [comment]
just confirmed this with a hue group too.

initial state: group off -> grayscale
switch group on -> grayscale
switch group off -> color

**Comment by mrsnyds** [comment]
> Sadly I didn't get it working... Your link is broken and I cannot find the "lovelace-card-templater" module...
> I tried it with other cards - but without any success...

Sorry about that broken link.  It worked when I posted, but the repository no longer exists.   Bad news for me because I really liked the way that card worked!    

Also, I can confirm the same as what you stated:  if the `entity:`  for the `picture-glance ` is a single light, and not a group or a light group, then it works as expected ... but you really want it to be a group of some sort if the card has multiple entities.

**Comment by iantrich** [comment]
That's weird, the dev just deleted their full account. Probably didn't care for bug reports 😄 

You can use my [config-template-card](https://github.com/custom-cards/config-template-card) which is the same concept but is javascript templates instead of jinja

**Comment by mrsnyds** [comment]
Thanks.   I had just become comfortable with jinja, and haven't really learned js, but I'll give that a whirl.

**Comment by iantrich** [comment]
https://community.home-assistant.io/t/lovelace-card-templater-card-jinja2-card-templating-in-lovelace/114268/7

Looks like it should be back up soon

**Comment by cotwild** [comment]
@mrsnyds
I somehow still struggle getting the config-template-card to work...? Any ideas?
Module is installed as instructed (https://github.com/custom-cards/config-template-card) - this isn't my first module/js...

I tried the "- entity: light.led_dusche ...." form under entities, I removed the hold_action... still not working.

![image](https://user-images.githubusercontent.com/8470092/58244362-ba6ce600-7d52-11e9-85ef-5677beb2d8dc.png)

Here is the part in the ui-lovelace.yaml:
```
              - type: 'custom:config-template-card'
                entities:
                  - light.licht_dusche
                card:
                  - type: 'picture-glance'
                    title: "Dusche"
                    entities:
                      - sensor.temperature_158d000272cee3
                      - sensor.humidity_158d000272cee3
                      - light.spiegelschrank_dusche
                      - light.spot_dusche_fenster
                      - light.spots_dusche
                      - entity: light.led_dusche
                        name: LED Dusche
                      - cover.dusche
                      - cover.dusche_fenster
                    entity: light.licht_dusche
                    state_image:
                      "on": /local/dusche_light_on.png
                      "off": /local/dusche_light_off.png
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
```

**Comment by cotwild** [comment]
Ok - I noticed that the "card-templater"is available again... but I got still no luck...

![image](https://user-images.githubusercontent.com/8470092/58245709-b393a280-7d55-11e9-82e0-072e0a4eef14.png)

```
              - type: 'custom:card-templater'
                entities:
                  - light.spot_dusche_fenster
                card:
                  - type: entities
                    title: Test
                    entities:
                      - entity: light.spot_dusche_fenster
                        name: fenster
              - type: 'custom:card-templater'
                entities:
                  - light.licht_dusche
                card:
                  - type: 'picture-glance'
                    title: "Dusche"
                    entities:
                      - sensor.temperature_158d000272cee3
                      - sensor.humidity_158d000272cee3
                      - light.spiegelschrank_dusche
                      - light.spot_dusche_fenster
                      - light.spots_dusche
                      - entity: light.led_dusche
                        name: LED Dusche
                      - cover.dusche
                      - cover.dusche_fenster
                    entity: light.licht_dusche
                    state_image:
                      "on": /local/dusche_light_on.png
                      "off": /local/dusche_light_off.png
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
```

Is that module incompatible with some other modules? Here my list of used modules/js:

```
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /local/kiosk.js
    type: js
  - url: /local/surveillance-card.js?v=0
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js
  - url: /customcards/github/thomasloven/popup-card.js?track=true
    type: js
  - url: /local/card-modder.js?v=0.1
    type: js 
  - url: /local/mini-graph-card-bundle.js?v=0.3.3
    type: module
  - url: /local/light-entity-card.js?track=true
    type: js
  - url: /local/custom/bar-card.js?v=1.0.0
    type: js
  - url: /local/slideshow-card.js
    type: js
  - url: /local/config-template-card.js
    type: module
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /local/useful-markdown-card.js
    type: js
  - url: /customcards/github/gadgetchnnel/lovelace-card-templater.js?track=true
    type: js
```
