### ISSUE TITLE
Selected tab's contents being displayed below previously selected tab's contents

### ISSUE THREAD

**Issue by LouisMT** [home-assistant/home-assistant-polymer#3204]
**Home Assistant release with the issue:** 0.93.1

**Last working Home Assistant release (if known):** unknown

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:**
* Kubuntu 19.04 + Firefox 66.0.5
* Kubuntu 19.04 + Chromium 73.0.3683.103
* Android 9 + Google Chrome 74.0.3729.157

**Description of problem:**
When returning to the overview page from any other page, the contents of the current tab are displayed below the contents of the previously selected tab, except if the previously selected tab was the `default_view` tab.

This is confusing because the selected tab's contents are always outside the viewport, making it seem like there's nothing happening (especially on mobile where there is no visible scroll bar).

Steps to reproduce:
1. Open any tab other than `default_view` ([screenshot 1](https://user-images.githubusercontent.com/1782761/57973720-a705f780-79ad-11e9-97fd-8e753aed5f4a.png))
1. Open any page other than the overview (e.g. the info page, [screenshot 2](https://user-images.githubusercontent.com/1782761/57973721-aa00e800-79ad-11e9-832f-403a81cf55dd.png))
1. Open the overview page ([screenshot 3](https://user-images.githubusercontent.com/1782761/57973723-acfbd880-79ad-11e9-9038-392e10b6c350.png), [screenshot 4](https://user-images.githubusercontent.com/1782761/57973725-aff6c900-79ad-11e9-8072-d7df3a272501.png))

Switching tabs keeps displaying the selected tab's content under the previously selected tab's content, until the previously selected tab is selected again. So it seems that Home Assistant partially forgets the current tab when switching pages.

**Javascript errors shown in the web inspector (if applicable):** not applicable

**Additional information:** 
Used configuration (with default Docker configuration):
```yaml
default_view:
  view: true
  icon: mdi:home-floor-0
  entities:
    - group.group_a

floor_1:
  view: true
  icon: mdi:home-floor-1
  entities:
    - group.group_b

floor_2:
  view: true
  icon: mdi:home-floor-2
  entities:
    - group.group_c

group_a:
  name: Group A
  entities:
    - sun.sun

group_b:
  name: Group B
  entities:
    - sensor.yr_symbol

group_c:
  name: Group C
  entities:
    - person.louis
```
