### ISSUE TITLE
ResizeObserver loop limit exceeded on HA 0.93.2 with Chrome 74.0.3729.169

### ISSUE THREAD

**Issue by chomupashchuk** [home-assistant/home-assistant-polymer#3222]
I have a page with picture-elements with a conditional card inside, where icon triggers "more-info" for the group, which includes input_number. Issue seen on latest Chrome
It triggers event:
https://########/lovelace/floorplan:0:0 ResizeObserver loop limit exceeded

ui-lovelance part within picture-elements:
```
          - type: conditional
            conditions:
              - entity: group.heating
                state: 'on'
            elements:
              - entity: group.heating
                icon: mdi:radiator
                style:
                  '--iron-icon-fill-color': '#FF0000'
                  left: 67%
                  top: 40.5%
                tap_action:
                  action: more-info
                type: icon
```

group part:
```
group:
  heating:
    view: true
    name: Heating
    icon: mdi:radiator
    entities:
      - switch.heater
      - sensor.time_remaining_heater
      - input_number.slider_heater
      - switch.towel_warmer
      - sensor.time_remaining_towel_warmer
      - input_number.slider_towel_warmer
```

The event is NOT seen on page, where slider is an entity within the card:
```
      - entities:
          - entity: switch.heater
          - entity: sensor.time_remaining_heater
          - entity: input_number.slider_heater
        show_header_toggle: false
        title: Bath Radiator
        type: entities
      - entities:
          - entity: switch.towel_warmer
          - entity: sensor.time_remaining_towel_warmer
          - entity: input_number.slider_towel_warmer
        show_header_toggle: false
        title: Towel Warmer
        type: entities
```
