### ISSUE TITLE
Markdown card: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by hAmpzter** [home-assistant/home-assistant-polymer#3260]
**Home Assistant release with the issue:**

0.94.1

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace UI: Latest

**Browser and Operating System:**

Chrome, latest (Version 74.0.3729.169)

**Description of problem:**

The markdown card gives error and does not seem to work properly because of that. In some cases it does not even render.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Er (chunk.cfddae4e0bcd25706f5c.js:5516)
    at HTMLElement.value (chunk.cfddae4e0bcd25706f5c.js:5560)
    at chunk.cfddae4e0bcd25706f5c.js:5530
    at Array.map (<anonymous>)
    at HTMLElement.value (chunk.cfddae4e0bcd25706f5c.js:5530)
    at HTMLElement.update (app.29ef27ad.js:2)
    at HTMLElement.performUpdate (app.29ef27ad.js:2)
    at HTMLElement._enqueueUpdate (app.29ef27ad.js:2)
```

**Additional information:**
Noticed this when using the markdown in the entities card:
```
type: entities
title: 'Markdown test'
show_header_toggle: false
entities:
  - type: section
    label: 'Working?'
  - type: markdown
    content: 'Time left:'
```

This also gives another error:
```
Your config is not supported by the UI editor:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.type` but received `"section"`.
Falling back to YAML editor.
```
