### ISSUE TITLE
Groups not reload after idle time

### ISSUE THREAD

**Issue by dacool** [home-assistant/home-assistant-polymer#3271]
**Home Assistant release with the issue:**
0.94.0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Ubuntu 18.04.2 LTS

**Component/platform:**
http

**Description of problem:**
If you leave homeassistant tab at web browser to idle at background, or open homeassistant ios app after it has been closed/background. The  old group where you was last time stays static at upper page, and when changing group tab, the new group opens at the bottom of page. And homeassistant makes 2 hui-view. You can reload page with F5 to fix problem, or reload button at ios app. No errors at log files, and the groups.yaml seems to be ok, with yamllint.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
http:
  ssl_certificate: /home/homeassistant/dehydrated/certs/_host.domain.com_/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/_host.domain.com_/privkey.pem
  base_url: _host.domain.com_:8123
  ip_ban_enabled: true
  login_attempts_threshold: 3

group: !include groups.yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
![ha_bug](https://user-images.githubusercontent.com/9551098/59420033-cc332d80-8dd4-11e9-9960-e7ae36280ef1.png)
