### ISSUE TITLE
View with group of groups shows inner groups as well

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/home-assistant-polymer#3279]
**Home Assistant release with the issue:** 0.89.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):** Lovelace auto-gen mode (= states?)

**Browser and Operating System:** Win 10, Firefox 67.0.2, 64 bit

**Description of problem:**

This package reproduces the bug:
```
group:
  test_group1:
    entities:
    - automation.alarmanlage
  test_group2:
    entities:
    - group.test_group1
  view_test:
    view: yes
    entities:
    - group.test_group2
```

1. The view shows not only the test_group2, but also the test_group1.
2. The group2 switch control does not reflect the actual state. Also toggling the switch does not influce the states of automation.alarmanlage.

I cleared the cache and offline data for my browser, to no avail.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
This is not an issue on IE or Firefox mobile.

Maybe this is related? https://github.com/home-assistant/home-assistant-polymer/issues/187
