### ISSUE TITLE
Lovelace: weblink component link not clickable

### ISSUE THREAD

**Issue by metbril** [home-assistant/home-assistant-polymer#3322]
**Home Assistant release with the issue:**
0.95.4

**Last working Home Assistant release (if known):**
?

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox 67.x
Brave 0.65.x

**Description of problem:**
A weblink entity does show name and link as text, but there is no clickable link
Same for Lovelace in UI mode or YAML mode.

Related to #2440 / #2437 ?

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

configuration.yaml
```yaml
weblink:
  entities:
    - name: Pi-Hole
      url: http://hassio.local:4865/
```

ui-lovelace.yaml
```yaml
  - entities:
      - entity: sensor.pi_hole_ads_blocked_today
      - entity: sensor.pi_hole_ads_percentage_blocked_today
      - entity: weblink.pi_hole
    show_header_toggle: false
    title: pi Hole
    type: entities
```
<img width="372" alt="Schermafbeelding 2019-06-30 om 21 18 04" src="https://user-images.githubusercontent.com/559346/60401076-9e900780-9b7c-11e9-9be1-4d29e6e31af5.png">

**Comment by SeanPM5** [comment]
You appear to be following the old "States" UI style - in Lovelace weblinks are handled a bit differently, you now specify them right in the entities section of your `ui-lovelace.yaml` file (and without needing the `configuration.yaml` entry) like this: 

```
  - type: entities
    title: Pi-Hole
    entities:
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - type: weblink
        name: Pi-Hole Admin
        url: http://hassio.local:4865/
        icon: mdi:pi-hole
      - sensor.pi_hole_domains_blocked
```
