### ISSUE TITLE
state_filter not working for locks and covers

### ISSUE THREAD

**Issue by j0dan** [home-assistant/home-assistant-polymer#3344]
Version 0.95.4

My entity-filter cards can only filter certain types of entities. I can filter presence or some sensors, but covers and locks won't show up when using a state_filter.

In the below example, only the sensor.zone_001 will show up.

```
entities:
  - entity: sensor.zone_001
  - entity: cover.garage_door
  - entity: lock.office_door_lock
state_filter:
  - Unlocked
  - Normal
  - Violated
  - Closed
  - Open
  - true
  - false
  - on
  - off
type: entity-filter
```
