### ISSUE TITLE
Home Assistant Frontend Doesn't Load On macOS Safari with version 0.98.1

### ISSUE THREAD

**Issue by btbutts** [home-assistant/home-assistant-polymer#3574]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**

N/A new install

**Operating environment (Hass.io/Docker/Windows/etc.):**

**Component/platform:**

**Description of problem:**

- From iOS devices using Safari, Chrome, Edge, or the HA app I can successfully authenticate and login and **load** the frontend.

- From Windows using Chrome, Firefox, or Edge, I can load the frontend.

- From macOS Mojave 10.14.6 using Safari, Chrome, or Firefox, I can't load the frontend.  I am able to get to the authentication page but the authentication does not work from this OS only.  I have tested this on two Macs.  The logs show that the device has not authenticated correctly.  I KNOW this is not true.  I am using a password app and have also tried typing it in correctly.  The page loads with just a blue bar at the top of the screen and a white background even so.  I even added the subnet the Macs are on to the trusted_networks and I got the same behavior.

- There definitely seems to be an issue with the authentication from Mac Devices.  I am not using SSL and I haven't changed the port from 8123.  The HA instance is new and still very default and out-of-the-box.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Edit Home Assistant Components
config:

# Web Front End
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.99.0/24
        - 127.0.0.1
      allow_bypass_login: true
    - type: homeassistant
  latitude: 36.6197
  longitude: -87.3623
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

discovery:
  enable:

# iPhone Tracking
ios:

# nmap tracking
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.99.0/24
    home_interval: 10
    exclude:
      - 127.0.0.1

**Traceback (if applicable):**
```

```

**Additional information:**
