### ISSUE TITLE
LL view in panel mode shows no background image

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#3705]
**Home Assistant release with the issue:**
0.99.0b0

**Last working Home Assistant release (if known):**
0.98.5

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
FF and Chrome confirmed.

**Description of problem:**
Add a view with background image and a simple markdown card.
```
  - title: Panelview
    background: center / cover no-repeat url("/local/pictures/backgrounds/sunset01.jpg") fixed
    #panel: true
    cards:
      - type: markdown
        content: some text
```
![20190912_21:12:28_001](https://user-images.githubusercontent.com/26381449/64814082-17f79d80-d5a3-11e9-8d11-98f69aa86dc5.png)

Now enable panel mode
```
    panel: true
```
![20190912_21:13:42_001](https://user-images.githubusercontent.com/26381449/64814125-2940aa00-d5a3-11e9-9753-583e398d64fe.png)

The background image doesn't show anymore.
An empty panel view shows the background image, after adding the first card, it's gone.
