### ISSUE TITLE
Thermostat card doesn't look good when it is small (unneeded padding)

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant-polymer#3711]
When You add multiple thermostats stacked they have padding and font size problems:
Open official demo (https://demo.home-assistant.io/#/lovelace/0)
add this card:
```
type: vertical-stack
cards:
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
```

You will get this look:
![image](https://user-images.githubusercontent.com/1741838/64861317-eaa50100-d62f-11e9-88cd-5f9b2c5f6f20.png)

As you can see icons are cut on the bottom.

ha-card is getting the correct class (`small`), but there is unneeded padding-top for `modes` class. After removing this padding card look much better:
![image](https://user-images.githubusercontent.com/1741838/64861481-56876980-d630-11e9-9050-9cc11bc4c2a8.png)

My proposition is to remove padding when ha-card has `small` class (or add padding when ha-card has `large` class).

Also please consider changing font size based on container size, as suggested here: https://github.com/home-assistant/ui-schema/issues/221#issuecomment-530862458, because right now `title` and `current-mode` are getting too large.
