### ISSUE TITLE
Nested group (state-card): Data will be not refreshed

### ISSUE THREAD

**Issue by tringler** [home-assistant/home-assistant-polymer#384]
Hello,

it is expected, that if nested group / state-card is opened data will be not refreshed (i.e. sensor data)?

![image](https://user-images.githubusercontent.com/4985268/29449806-7aad1dc4-83fc-11e7-8143-66076f9bab41.png)

For instance i'm using the example described in the HASS documentation at the end of this page https://home-assistant.io/components/input_slider/:
```
# Example configuration.yaml entry using 'input_slider' in an action in an automation
   
# Define input_slider
input_slider:
  target_temp:
    name: Target Heater Temperature Slider
    min: 1
    max: 30
    step: 1
    unit_of_measurement: step  
    icon: mdi:target

# Automation.     
 # This automation script runs when a value is received via MQTT on retained topic: setTemperature
 # It sets the value slider on the GUI. This slides also had its own automation when the value is changed.
- alias: Set temp slider
  trigger:
    platform: mqtt
    topic: "setTemperature"
   # entity_id: input_slider.target_temp
  action:
     service: input_slider.select_value
     data_template:
      entity_id: input_slider.target_temp
      value: '{{ trigger.payload}}'

 # This automation script runs when the target temperature slider is moved.
 # It publishes its value to the same MQTT topic it is also subscribed to.
- alias: Temp slider moved
  trigger:
    platform: state
    entity_id: input_slider.target_temp
  action:
    service: mqtt.publish
    data_template:
      topic: "setTemperature"
      retain: true
      payload: '{{ states.input_slider.target_temp.state | int }}'

```
If I add a sensor for that mqtt value and put both in a group everything is working fine as long the group is on the mainpage:

```
sensor:
  - platform: mqtt
    state_topic: "setTemperature"
    name: temp_sensor
```
```
group:
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - group.set_target_temp
  
  set_target_temp:
    name: sensor
    entities:
      - input_slider.target_temp
      - sensor.temp_sensor
```

But if I nest the group the sensor is not updating while I opened the group (state-card) in the Home Assistant Panel:

```
group:
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - group.temps

  temps:
    name: temps
    entities:
      - group.set_target_temps
  
  set_target_temp:
    name: sensor
    entities:
      - input_slider.target_temp
      - sensor.temp_sensor
```
If I move the slider in that nested group now the sensor will be not updated. I need to move the slider, close the nested group (state-card), open it again and now it is updated.
