### ISSUE TITLE
Ability to show the temperature/humidity state value in a picture-glance footer

### ISSUE THREAD

**Issue by mnoorenberghe** [home-assistant/home-assistant-polymer#3901]
```yaml
      - type: picture-glance
        title: Living Room
        camera_image: camera.livingroom
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_humidity
```

The temperature/humidity entities will show as their icons (🌡 %) but I actually need to click on them to see the current temperature and humidity values. It would be nice if I could just see the values at a glance right in the footer overlay and click on those numbers if I want to see the overlay card. I would also be fine with showing the numbers (with units) beside the icons to it's clear what the percentage is for when there are multiple percentages.

I'm willing to make pull requests if there is agreement that this is more useful than just the icons.
