### ISSUE TITLE
switch paper-toggle-button to mwc-switch #3683 breaks my theme using `paper-toggle-button-checked-button-color`

### ISSUE THREAD

**Issue by rhoppel** [home-assistant/home-assistant-polymer#3989]
**Home Assistant release with the issue:**

100.1

**Last working Home Assistant release (if known):**
99.0
**UI (States or Lovelace UI?):**

Lovelace ui change
Cause: Switch paper-toggle-button to mwc-switch #3683
**Browser and Operating System:**

**Description of problem:**

- the change to  "mwc-switch" breaks my theme style `paper-toggle-button-checked-button-color`
- I have been using my own color to brightly indicate a toggle switch in the "ON" position
- this style is now being controlled by `--mdc-theme-secondary: var(--primary-color);` I don't want this
- I would like to use `--mdc-theme-secondary: var(--accent-color)`
- I tried to over-ride this using `mdc-theme-secondary` but putting this in my theme.yaml keeps getting over-written such that it has no effect
- How do I get control of this style? I love my theme and want it back.
- using the `var(--accent-color)` for checked toggles make it much easier to see the switches which are turned on at a quick glance
I have been using the following in my custom theme.yaml for toggle switch styling.
```yaml
  paper-toggle-button-checked-ink-color: var(--make-light-blue)
  paper-toggle-button-checked-button-color: var(--make-orange)
  paper-toggle-button-checked-bar-color: var(--make-dark-monokai)
  paper-toggle-button-unchecked-ink-color: var(--make-light-blue)
  paper-toggle-button-unchecked-button-color: var(--make-light-blue)
  paper-toggle-button-unchecked-bar-color: var(--make-dark-monokai)
```
I created my theme based on css used in previous themes and it looks great. I was not aware why things are the way they are. "paper" variables are used all over the place in HA themes.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
