### ISSUE TITLE
Panel mode map not in center

### ISSUE THREAD

**Issue by i00** [home-assistant/home-assistant-polymer#4005]
**Home Assistant release with the issue:**
0.100.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Integration:**
[Map](https://www.home-assistant.io/integrations/map/)

**Description of problem:**
When a page is in panel mode, the map assumes that it is square (I think), and the items are either lost off the bottom of the display or not centered, on a rectangular screen.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
- icon: 'mdi:map'
  panel: true
  path: map
  title: Map
  badges: []
  cards:
    - card:
        type: map
      filter:
        include:
          - attributes:
              source_type: gps
            entity_id: device_tracker.*
          - entity_id: zone.home
      type: 'custom:monster-card'
```

**Additional information:**
In the above example I am using a monster card to filter entities, but this also happens when I just use the standard map.

**Comment by iantrich** [comment]
We only support core cards so please include a configuration that does not include custom cards

**Comment by i00** [comment]
OK ... I was somewhat incorrect ... it can happen with stock components like this:
````YAML
  - icon: 'mdi:map'
    path: map2
    title: Map2
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: map
            entities:
              - entity: zone.home
              - entity: device_tracker.kris_alexander_bennett_phone
````
... it doesn't happen with the standard map ... only when a card is embedded **within** another card...
The map wants to remain square (like it does when not in panel mode) rather than filling the space (as should happen in panel mode)
