### ISSUE TITLE
Map wants to be square in panel mode when embedded in another card

### ISSUE THREAD

**Issue by i00** [home-assistant/home-assistant-polymer#4011]
**Home Assistant release with the issue:**
0.100.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Integration:**
[Map](https://www.home-assistant.io/integrations/map/)

**Description of problem:**
The map wants to remain square (like it does when not in panel mode) rather than filling the space (as should happen in panel mode)
It happens when a card is embedded **within** another card

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
````YAML
  - icon: 'mdi:map'
    path: map2
    title: Map2
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: map
            entities:
              - entity: zone.home
              - entity: device_tracker.kris_alexander_bennett_phone
````
