### ISSUE TITLE
Map within another card on panel mode page wants to be square

### ISSUE THREAD

**Issue by i00** [home-assistant/home-assistant-polymer#4020]
**Home Assistant release with the issue:**
0.100.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Integration:**
[Map](https://www.home-assistant.io/integrations/map/)

**Description of problem:**
When a map is within another card (e.g. vertical-stack), and the page is set to panel mode, the map scrolls past the view area in the web browser as it still wants to be "square".

```yaml
  - icon: 'mdi:map'
    path: map2
    title: Map2
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: map
            entities:
              - entity: zone.home
              - entity: device_tracker.kris_alexander_bennett_phone
```
