### ISSUE TITLE
automatically generated views by area and/or domain

### ISSUE THREAD

**Issue by iantrich** [home-assistant/home-assistant-polymer#4021]
Option to set a view as an `auto` view that is either determined by a particular `area` and/or `domain
```yaml
views:
  - title: Kitchen
    area: kitchen
  - title: Lights
    domain: light
```
