### ISSUE TITLE
Add "action_name" option to entities card for scenes and scripts

### ISSUE THREAD

**Issue by sander76** [home-assistant/home-assistant-polymer#4080]
a service call entry inside an entities card allows for modifying the default `RUN` action name.

```
entities:
  - type: call-service
    icon: mdi:power
    name: Bed light
    action_name: Toggle light
    service: light.toggle
    service_data:
      entity_id: light.bed_light
```

I'd like to see this option for `script` and `scene` entities as well.

```
entitites:
  - entity: script.a_script
    action_name: "Go for it !"
  - entity: scene.a_scene
    action_name: "Do the scene"
```
