### ISSUE TITLE
Timestamp shows "Invalid Date" in Safari; but it's properly displayed in Chrome

### ISSUE THREAD

**Issue by mikeage** [home-assistant/home-assistant-polymer#4110]
**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):**
n/a

**Operating environment (Hass.io/Docker/Windows/etc.):**
Safari 13.0 on Mac OS 10.14.6, Chrome 77.0.3865.120 on the same Mac OS

**Integration:**
custom-component/alexa_media_player, but seems to be related to the display, not the sensor

**Description of problem:**
I use the Alexa Media Player to create some sensors with timestamps (next alarm, reminder, etc). When placed into an entity card, in Safari, I see `Invalid Date` where in Chrome I see a value like `In 10 minutes` or `In 20 hours`. Clicking on the sensor gives values like `2019-10-23 09:51:00+03:00` in both Chrome and Safari

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: amazon.com
      debug: True
      exclude_devices:
        - "This Device"
```
Lovelace card configuration:
```yaml
entities:
  - entity: sensor.parents_room_next_reminder
  - entity: sensor.parents_room_next_timer
  - entity: sensor.parents_room_next_alarm
title: Alexa Test
type: entities
```

**Traceback (if applicable):**
n/a

**Additional information:**
Original issue was https://github.com/custom-components/alexa_media_player/issues/446, but it seems to be a front-end issue, and only on one browser.
