### ISSUE TITLE
Badge 'name' property not overwriting entity's 'friendly_name' in 0.101.1

### ISSUE THREAD

**Issue by alexmuntean** [home-assistant/home-assistant-polymer#4163]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
Home Assistant 0.101.1

**Last working Home Assistant release (if known):**
Home Assistant 0.100.3
**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
safari, chrome, macos

**Description of problem:**
I'm setting the badge names in raw config editor like this:

```
  - badges:
      - sun.sun
      - entity: sensor.kitchen_feels_like
        name: Bucatarie
      - entity: sensor.living_room_feels_like
        name: Living
      - entity: sensor.ground_floor_bathroom_feels_like
        name: Baie jos
      - entity: sensor.alex_bedroom_feels_like
        name: Alex
      - entity: sensor.cristina_bedroom_feels_like
        name: Cristina
      - entity: sensor.daria_bedroom_feels_like
        name: Daria
      - entity: sensor.upstairs_bathroom_feels_like
        name: Baie sus
      - entity: sensor.disk_use_percent
        name: Disk usage
      - entity: sensor.cpu_temperature
        name: CPU Temp
```
and the names are not overwritten. I keep getting the old names

**Javascript errors shown in the web inspector (if applicable):**
no errors

**Additional information:**
<img width="582" alt="image" src="https://user-images.githubusercontent.com/2796003/68011409-eee4b680-fc8f-11e9-8d31-3b58fd3c667b.png">
