### ISSUE TITLE
Entity filter badge in LL view needs page refresh

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4183]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.2

**Last working Home Assistant release (if known):**
None, new feature in 0.101

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox on Ubuntu

**Description of problem:**
Simple view for playing with the new entity filter badge
```yaml
  - title: Badges Test
    path: badges-test
    badges:
      - type: entity-filter
        entities:
          - entity: switch.mqtt_test1
          - entity: switch.mqtt_test2
        state_filter:
          - 'on'
    cards:
      - type: entities
        entities:
          - entity: switch.mqtt_test1
          - entity: switch.mqtt_test2
        title: Test Switches
```
After toggle of the switches the page needs a reload (F5 in Storage mode) to reflect the state changes.
![20191104_16:07:49_001](https://user-images.githubusercontent.com/26381449/68131664-b528df80-ff1d-11e9-8ff6-b6b51111f036.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
