### ISSUE TITLE
NaN JSON values break loading the frontend

### ISSUE THREAD

**Issue by Heronimonimo** [home-assistant/home-assistant-polymer#4191]
**Home Assistant release with the issue:**

0.101.3

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio
**Integration:**

https://www.home-assistant.io/integrations/integration/

**Description of problem:**
When the integration sensor spits out an NaN value the frontend won't load and hangs on "Loading data". In the logs it shows the error:
"Unable to serialize to JSON: Out of range float values are not JSON compliant"

After removing the specific statistics sensor the frontend the problem was resolved. It seems to be closely related to home-assistant/home-assistant#20715

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
  - platform: statistics
    entity_id: sensor.gas_usage
    name: gas_stats
    max_age:
      hours: 24          
    sampling_size: 1000
```

**Traceback (if applicable):**
```

```

**Additional information:**
