### ISSUE TITLE
Manual alarm_control_panel PIN not cleared if input with keyboard

### ISSUE THREAD

**Issue by darknicht66** [home-assistant/home-assistant-polymer#4232]
**Home Assistant release with the issue:** 0.101.3

**Last working Home Assistant release (if known):** Unknown

**Operating environment (Hass.io/Docker/Windows/etc.):** Hass.io on Ubuntu 18.04

**Integration:**

Manual Alarm Control Panel
https://www.home-assistant.io/integrations/manual/

**Description of problem:**
When entering a PIN using the onscreen numeric keypad (mouse or touchscreen) and hitting an 'arm'/'disarm' button, the action is performed and the PIN is cleared from the screen. The PIN must then be re-entered to perform the next 'arm'/'disarm' action. This is the expected function.
If, however, the PIN is entered using a keyboard (select the 'alarm code' field and use physical keyboard for numeric entry), upon selecting 'arm'/'disarm' the function fires, but the PIN field is not cleared. The PIN remains and you can repeatedly ARM/DISARM the system without the need to re-enter the PIN.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
- platform: manual
  name: Security System
  code: !secret security_system_code
  code_arm_required: true
  delay_time: 0
  pending_time: 60
  trigger_time: 120
  disarm_after_trigger: false
  disarmed:
    trigger_time: 0
  armed_home:
    delay_time: 0
    pending_time: 0

```

**Traceback (if applicable):**
```

```

**Additional information:**
