### ISSUE TITLE
[0.102.0b1] Scene editor does not save effect of light

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/home-assistant-polymer#4238]
**Home Assistant release with the issue:** 0.102.0b1

**Last working Home Assistant release (if known):** none

**Operating environment (Hass.io/Docker/Windows/etc.):**

**Integration:** scene editor

**Description of problem:**
When I use the new scene editor, many parameters of a light are saved, but not the selected effect.
![Screenshot_2019 11 14_19h46m01s_002_](https://user-images.githubusercontent.com/1368405/68886490-9a254f00-0717-11ea-8868-a2631adb8d7f.png)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
Output of the editor:
```yaml
scene:
  - id: '1573757176173'
    name: Test
    entities:
        light.wg_hintergrund_1:
        brightness: 46
        color_temp: 500
        hs_color:
        - 30.601
        - 94.547
        rgb_color:
        - 255
        - 136
        - 13
        state: 'on'
        xy_color:
        - 0.599
        - 0.382
```
