### ISSUE TITLE
Visible behave wrong

### ISSUE THREAD

**Issue by GhostNr1** [home-assistant/home-assistant-polymer#4330]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Home Assistant release with the issue:**
Home Assistant 0.102.3

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome OS and Android phones

**Description of problem:**

When I set the visible in my view file the UI is displaying correctly but the behavior is wrong. If I have one user that shouldn't see the first view and it login it will always start at this first view and can then navigate to it's own view but not select the first one any more.
If I add a new user and all the different views has a set visible. When this user login it will start to see the first view but can't see any view to select.  

**Expected behaviour:**

When I have added visible and added a specific user no other user should be able to see that view. If I add a new user and login I should see a blank view and don't get a default one. 

**Relevant config:**
```
title: Home
views:
  - path: default_view
    title: Home
    visible:
      - user: 9ba70da94dcb4254bf60ac5fbb15a56d
    icon: 'mdi:home'
    badges:
      - entity: sun.sun
    cards:
      - entity: weather.smhi_home
        type: weather-forecast
      - entities:
          - entity: switch.gillestuga_langst_in
          - entity: switch.gillestugan_langst_ut
          - entity: switch.gillestugan_mitt
          - entity: switch.hydroponic_light
        title: Switch downstair
        type: entities
  - title: Title 1
    visible:
      - user: 8f9cbc067cc4404491cfe4426df2f373
    icon: 'mdi:human-female'
    badges: []
    cards:
      - entities:
          - entity: switch.gillestuga_langst_in
          - entity: switch.gillestugan_mitt
          - entity: switch.gillestugan_langst_ut
          - entity: switch.hydroponic_light
        show_header_toggle: true
        title: Lampor nere
        type: entities
```

**Steps to reproduce this problem:**

1. Add more then 1 user
2. Have more then 1 view
3. Add visbile in all the views and add user to visible
4. Try to login with the different users and see that you get different views

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
