### ISSUE TITLE
Manifest: property 'theme_color' ignored, 'var(--text-color)' is not a valid color

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-polymer#4358]
**Home Assistant release with the issue:**

103.0

**Last working Home Assistant release (if known):**

don't know, reported earlier (but cant find it ....)
**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio Rpi4
**Integration:**

**Description of problem:**
Upon loading HA, inspector shows:
```
Manifest: property 'theme_color' ignored, 'var(--text-color)' is not a valid color
```

seems a non user related issue, wouldn't know what theme or color setting this could cause.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**

checking the manifest code in inspector reveals:
```
{"background_color": "#FFFFFF", "description": "Home automation platform that puts local control and privacy first.", "dir": "ltr", "display": "standalone", "icons": [{"purpose": "maskable any", "sizes": "192x192", "src": "/static/icons/favicon-192x192.png", "type": "image/png"}, {"purpose": "maskable any", "sizes": "384x384", "src": "/static/icons/favicon-384x384.png", "type": "image/png"}, {"purpose": "maskable any", "sizes": "512x512", "src": "/static/icons/favicon-512x512.png", "type": "image/png"}, {"purpose": "maskable any", "sizes": "1024x1024", "src": "/static/icons/favicon-1024x1024.png", "type": "image/png"}], "lang": "en-US", "name": "Home Assistant", "short_name": "Assistant", "start_url": "/?homescreen=1", "theme_color": "var(--text-color)"}
```

**Additional information:**
![Schermafbeelding 2019-12-17 om 15 25 26](https://user-images.githubusercontent.com/33354141/71004064-d7e41180-20e1-11ea-93ad-354fd9379c51.jpg)

**Comment by bramkragten** [comment]
Please share your active theme, I think your primary color is a var instead of a color.

**Comment by Mariusthvdb** [comment]
thanks for chiming in! and though I never thought to check this based on changing themes, you're probably right, it only shows using this 'Clear' theme:

```
clear:
  name: 'Clear'
  # Colors
  text-color: '#636B75'                                                           # Grey text
  text-light-color: '#BAC0C6'                                                     # Light grey text
  accent-color: '#00a1ff'                                                         # Blue
  background-color: '#F7F8F9'                                                     # Light grey background
  background-color-2: '#F4F5F6'                                                   # Light grey background
  background-card-color: 'ivory' #'rgba(255,255,255,1.0)'                                  # White background
  border-color: '#EAEAEA'                                                         # Light grey border

  # Header
  primary-color: 'var(--text-color)'                                              # Background
  text-primary-color: '#FFF'                                                      # Text

  # Left Menu
  paper-listbox-background-color: 'var(--background-color)'                       # Background

  # UI
  paper-card-header-color: 'var(--text-color)'                                    # Title in settings
  primary-background-color: 'var(--background-color)'                             # Background (also title background in left menu)

  # Card
  paper-card-background-color: 'var(--background-card-color, 0.6)'                     # Background
#  paper-card-background-color: 'rgba(40, 40, 40, 0.6)'
#  dark-primary-color: 'var(--text-color)'
#  ha-card-border-radius: '6px'
  ha-card-box-shadow: '0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)'
  background-image: 'center / cover no-repeat url("/local/wallpapers/clear.jpg") fixed'
```

bingo, but how to change that using the var and not get an error? The theme does show alright, and, this error is only in Chrome inspector, not Safari

**Comment by bramkragten** [comment]
Replace `primary-color: 'var(--text-color)'` with a color (#636B75) and it is fixed.

**Comment by Mariusthvdb** [comment]
of course, that's the easy fix, but it hurts the use of the theme further down the system won't it? 
Would you say this theme is mal-configured  and is HA simply not allowing this type of var use in the themes?

Or is it a bug, and should it be fixed.

I ask because many people this theme, and it should be clear which way to go forward on this.

**Comment by bramkragten** [comment]
Primary-color is the main color so it is weird to have that defined by a var, I would say it should be turned around.

I don't think it is something we will fix.

**Comment by Mariusthvdb** [comment]
right, understood, thanks for explaining, makes sense ;-) Not sure why the author of the theme did that, have chimed him in, maybe he'll report back.

**Comment by Mariusthvdb** [comment]
Hey Bram, please let me ask this here, or tell me to open a new issue:

have the same error reported for:

```
Manifest: property 'theme_color' ignored, 'hsl(var(--huesat) 20%)' is not a valid color.
```

with relevant section in Matrix theme:

```
matrix:
  name: 'Matrix'
  # MyVariables
  base-hue: '120' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
  base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
  # MyVar
  huesat: 'var(--base-hue), var(--base-sat),'
  # Primary Color
  primary-color: 'hsl(var(--huesat) 20%)'
```

now this shows perfectly, and has done so for almost 3 years...

int this type of color yet supported somehow?
