### ISSUE TITLE
Thermostat card shows nothing when setpoint is set to 0.0

### ISSUE THREAD

**Issue by Guyohms** [home-assistant/home-assistant-polymer#4366]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103.0

**Last working Home Assistant release (if known):**
Not known

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox 71.0 on Windows 7

**Description of problem:**
As the title says, the setpoint value is not shown when it is set to 0.0.

Setpoint at 0.5:
![image](https://user-images.githubusercontent.com/44414660/71093224-cbf65f00-2176-11ea-9fb1-fa739f30fa65.png)

Setpoint at 0.0:
![image](https://user-images.githubusercontent.com/44414660/71093116-8cc80e00-2176-11ea-850d-bae9e21fe460.png)

**Expected behaviour:**
Shows 0.0

**Relevant config:**

```
  - platform: generic_thermostat
    name: Câble chauffant
    heater: switch.puits
    target_sensor: sensor.puits_ds18b20_2_temperature
    min_temp: -5
    max_temp: 15
    ac_mode: False
    cold_tolerance: 0.5
    hot_tolerance: 0.0
    min_cycle_duration:
      minutes: 2
    keep_alive:
      minutes: 1
    precision: 0.1
```

**Steps to reproduce this problem:**

1. Set the desired temperature to 0.0
