### ISSUE TITLE
Passing a variable to a script in a entities card does not work

### ISSUE THREAD

**Issue by FutureTense** [home-assistant/home-assistant-polymer#4369]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Home Assistant release with the issue:0.103.0 (docker image)**

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

**Browser and Operating System: Chrome/Ubuntu 18.04 running docker**

I'm trying to call the script `start_feeder_timer` and pass in `seconds` as a variable from lovelace.  The script below also creates a persistent_notification in order to see what the value for `seconds` was passed to the script. Also provided are two cards which call the script.

The first card, which displays a single entity-buton works as expected when clicked in the UI.  The timer starts with the correct duration and creates a persistent notification message which reads:
    **Timer duration**
	60

The second card, which is an entities card includes the timer and entity-button does not work when clicked in the UI.  It only creates a persistent notification which reads:
    **Timer duration**
	

The `seconds` variable is not making it to the script, even though the script is being called the same was in the first card.

I suspect the problem is in the entities-card code.

Script
```
start_feeder_timer:
  alias: 'Start feeder timer'
  description:  'Turn on feeder timer for number of seconds'
  fields:
    seconds:
      description: 'The number of seconds to turn on the feeder timer'
      example: '30'  
  sequence:
      # create notification for debugging seconds variable is caught by script
    - service: persistent_notification.create
      data_template:
        title: "Timer duration"
        message: "{{seconds}}"
      #cancel timer if it is already running
    - service: timer.cancel
      entity_id: timer.kitty_feeder_relay
      # start the timer for specified duration
    - service: timer.start
      data_template:   
         entity_id: timer.kitty_feeder_relay
         duration: "{{seconds}}"
```

Card 1 entity-button WORKS
```
entity: script.start_feeder_timer
icon: 'mdi:cat'
show_icon: true
show_name: true
tap_action:
  action: call-service
  service: script.start_feeder_timer
  service_data:
    seconds: 60
type: entity-button
```

Card 2 entities with entity-buton FAILS
```
entities:
  - entity: timer.kitty_feeder_relay
  - entity: script.start_feeder_timer
    icon: 'mdi:cat'
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: script.start_feeder_timer
      service_data:
        seconds: 30
    type: entity-button
type: entities
```

**Comment by iantrich** [comment]
```yaml
entities:
  - entity: timer.kitty_feeder_relay
  - entity: script.start_feeder_timer
    icon: 'mdi:cat'
    show_icon: true
    show_name: true
    tap_action:
      action: call-service
      service: script.start_feeder_timer
      service_data:
        seconds: 30
    type: entity-button
type: entities
```

This is not doing what you think it is doing:
1. `type: entity-button` is not a valid type for a row
2. Because of #1, you're actually just getting a standard script row (this is generated by looking at the domain of the entity), and by hitting the "EXECUTE" button, it just calls the script without arguments. The `tap_action` relates to the icon/name in the row. Clicking on either of those will cause the service to be called with the service_data passed along.
