### ISSUE TITLE
Lovelace entity button double_tap_action causing undesired behavior

### ISSUE THREAD

**Issue by Trumpiter** [home-assistant/home-assistant-polymer#4419]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue: 0.103.5

**Last working Home Assistant release (if known): unknown

**UI (States or Lovelace UI?): Lovelace UI

**Browser and Operating System: iOS 13.3 (issue occurs in Chrome, Safari, and the companion app)

**Description of problem:
I am attempting to use both tap_action to toggle a single light and double_tap_action to toggle all lights with an entity button in Lovelace. Currently, when both options are specified, they work perfectly on my laptop (Chrome on MacOS 10.14.6), but a single tap on my phone will produce the double tap action.

It looks like it might be related to this issue https://github.com/home-assistant/home-assistant-iOS/issues/431 and the subsequent fix https://github.com/home-assistant/home-assistant-polymer/pull/3523

Further testing: I changed the behavior of two separate entity buttons to further explore the behavior. One I set tap_action to toggle and double_tap_action to none and the second I set tap_action to none and double_tap_action to toggle. On MacOS, the behavior is as expected--the first button toggles with a single tap (and with a double tap) and the second button only toggles with a double tap. On iOS, both buttons toggle with single taps (and with double taps). 

TLDR: On ~~iOS~~ some devices, Lovelace UI does not differentiate between a single and a double tap, and when both actions are specified it defaults to double_tap_action.

**Expected behaviour: One tap -> tap_action. Double tap -> double_tap_action (or tap_action if no double_tap_action is specified)

**Relevant config:
```
double_tap_action:
  action: call-service
  service: light.toggle
  service_data:
    entity_id: group.all_lights
entity: light.bed
hold_action:
  action: more-info
tap_action:
  action: toggle
type: entity-button
```

**Steps to reproduce this problem:**

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**
