### ISSUE TITLE
Confirmation dialogue doesn't appear in mobile browser version 

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#4464]
**Checklist:**

- [*] I updated to the latest version available
- [*] I cleared the cache of my browser

**Home Assistant release with the issue:**
Home Assistant 0.103.6

Frontend version: 20191204.1 - latest
**Last working Home Assistant release (if known):**
unknown
**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Android mobile Chrome 79.0.3945.116

**Description of problem:**
I've added a confirmation option to a button to confirm the action, see code below. However, the action executes without the confirmation dialogue in the mobile browser version while it works correctly in the desktop version.

**Expected behaviour:**
The behavior should be consistent between the mobile and desktop versions, i.e. confirmation dialogue should appear to confirm the action.

**Relevant config:**
```
double_tap_action:
  action: toggle
entity: lock.door_lock
hold_action:
  action: more-info
show_icon: true
show_name: true
tap_action:
  action: toggle
  confirmation:
    text: Are you sure?
type: entity-button
```

**Steps to reproduce this problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
