### ISSUE TITLE
Light card in horizontal stack doesnt line up if brightness support difference

### ISSUE THREAD

**Issue by ryanwinter** [home-assistant/home-assistant-polymer#4552]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.104.0

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome + Windows 10

**Description of problem:**
If two light cards are added to a horizontal stack, and one support brightness and the other doesnt, then the icons and text don't align.

![Screenshot_20200121-112153](https://user-images.githubusercontent.com/10238039/72836652-ea51ed80-3c41-11ea-8f86-8f5e6f28a575.png)

**Expected behaviour:**
Icons and text align for all lights in a horizontal stack, regardless of supported features.

**Relevant config:**
```
  - cards:
      - entity: light.kitchen_lights
        type: light
      - entity: light.kitchen_lamp
        type: light
    type: horizontal-stack
```

**Steps to reproduce this problem:**
1. Create 2 light entities, one that supports brightness and one that doesn't.
2. Add both entities into a horizontal stack
3. Observe misalignment of icon and text.
