### ISSUE TITLE
New scene is not saved correctly when an integration is already present

### ISSUE THREAD

**Issue by vide** [home-assistant/home-assistant-polymer#4577]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

Scenes created via the UI are saved to disk (`scenes.yml` file) but are not displayed in the UI afterwards.
I've previously configured an external integration (`tuya`) which has some saved scenes inside and they are correctly imported (but not editable, nor present in `scenes.yml`)

## Expected behavior

I would expect the scene to be created, displayed in the Scene web UI and be available to be selected in the places where they can be used (i.e. Automations)

## Steps to reproduce

1. Add an external integration `tuya` with pre-existing scenes in it
2. Create a new scene via HA web UI
3. Check that there is no new Scene listed
4. Check that the Scene is present in `scenes.yml`

## Environment

- Home Assistant release with the issue: 0.142.3
- Last working Home Assistant release (if known): N/A
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version: Firefox 72 Linux
- Operating system: Raspbian

## Problem-relevant configuration

snippet from `configuration.yml`
```yaml
tuya:
  username: 111111111
  password: !secret smart_life
  country_code: 1
  platform: smart_life

```

test scene in `scenes.yml` as saved by HA
```yaml
- id: '1579789046326'
  name: test
  entities:
    media_player.tv_sala:
      entity_picture: /api/media_player_proxy/media_player.tv_sala?token=f473009098b10c9139f717b56409742731c232e7a549175c66be73dc61475b55&cache=d43932c511d4b4a0
      friendly_name: TV Sala
      is_volume_muted: false
      media_content_type: channel
      media_title: TV3HD
      source: LiveTV
      source_list:
      - DAZN
      - LiveTV
      - Netflix
      - TV3
      - YouTube
      state: 'on'
      supported_features: 20285
      volume_level: 0.09
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Extra behaviour: if I comment out the `tuya` integration from the config file, then I don't even get a "Scenes" link in the Configuration Dashboard

Home Assistant installed by the virtualenv method
