### ISSUE TITLE
Unknown type encountered: sensor in 0.105.0b0

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4670]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Refreshing the UI with the 3 dots menue sometimes shows the red cards
![20200130_13:30:06_001](https://user-images.githubusercontent.com/26381449/73450240-4b29a600-4365-11ea-882a-fbc5e32b3521.png)
the next time it shows the expected card
![20200130_13:30:27_001](https://user-images.githubusercontent.com/26381449/73450279-5b418580-4365-11ea-9dac-63f96711e0fb.png)

## Steps to reproduce

Not clear. Sometimes it shows the red cards after i open the browser, sometimes i have to refresh the UI multiple times.

## Environment

- Home Assistant release with the issue: 0.105.0b0
- Last working Home Assistant release (if known): 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Latest Firefox 72.0.2 and Chrome
- Operating system: Ubuntu

## Problem-relevant configuration

```yaml
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.e3dc_pv_total
                name: PV Gesamt
                icon: mdi:white-balance-sunny
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ sensor.daily_pv_energy.state ]] kWh"
              - entity: sensor.e3dc_house_power
                name: Haus
                icon: mdi:home-outline
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ sensor.daily_house_energy.state ]] kWh"
              - entity: sensor.e3dc_net_power
                name: Netz
                icon: mdi:transmission-tower
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Bezug: [[ sensor.daily_from_net_energy.state ]] kWh, Einsp.: [[ sensor.daily_to_net_energy.state ]] kWh"
              - entity: sensor.e3dc_battery_power
                name: Batterie
                icon: mdi:car-battery
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Ladung: [[ sensor.daily_to_battery_energy.state ]] kWh, Entl.: [[ sensor.daily_from_battery_energy.state ]] kWh"
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
I think it's the same problem like in this issue https://github.com/home-assistant/home-assistant-polymer/issues/4669, but that was closed in the moment i want to comment.

**Comment by VDRainer** [comment]
So, i can't reproduce the issue when i comment out the secondaryinfo-entity-row, but this is not used in https://github.com/home-assistant/home-assistant-polymer/issues/4669.
Is there a general issue with custom cards?

**Comment by bramkragten** [comment]
I would say custom element rows, checking the code now, but can't see a problem immediately. Any way I can easily reproduce this?

**Comment by bramkragten** [comment]
Ah, yeah, I see it

**Comment by bramkragten** [comment]
Or maybe not, would still help to be able to reproduce

**Comment by VDRainer** [comment]
Here's another one.
```
            entities:
              - entity: switch.e3dc
                name: S10-xxxxxxxxxxxx
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Firmware: [[ sensor.e3dc_firmware.state ]]"
```
![20200130_14:33:47_001](https://user-images.githubusercontent.com/26381449/73454246-f3dc0380-436d-11ea-9886-1ef37de962f7.png)
Normaly:
![20200130_14:36:08_001](https://user-images.githubusercontent.com/26381449/73454258-fa6a7b00-436d-11ea-9473-f5d8ae806a7a.png)

I simply click the 'Refresh' from the 3 dots menu multiple times, the red cards show up and at the bottom the LL Refresh bar is shown
![20200130_14:40:06_001](https://user-images.githubusercontent.com/26381449/73454655-ce032e80-436e-11ea-8db5-c5e0f7f00ae4.png)
After i click 'Refresh' on this bar, all cards are back to normal.

**Comment by bramkragten** [comment]
I think it is cardTools and not our code, cardTools seems to change the config at some points and it really shouldn't

**Comment by thomasloven** [comment]
Sorry about that. Should be fixed now.

**Comment by VDRainer** [comment]
Thanks @thomasloven , but after upgrade card-tools to v8, the red cards are always there, not sporadically on refresh. :confused: 
Should i open an issue in your repo?

**Comment by bramkragten** [comment]
That is probably because `secondaryinfo-entity-row` is built with cardTools 0.4

**Comment by iantrich** [comment]
I just upgraded card-tools and my errors are gone, but my configs had been updated with a `type: default` for rows I had not specified a type on. I removed those and it seems to be good now.

**Comment by Krocko** [comment]
@iantrich how did you do that? Can you please explain?

**Comment by iantrich** [comment]
Did I not?
1. update card-tools
2. clear browser cache
3. delete `type: default` where ever it shows up in lovelace configuration

**Comment by Krocko** [comment]
Thanks. But i don't have a `default`entry in my lovelace.

**Comment by VDRainer** [comment]
@iantrich , thanks for looking at this. After i update card-tools, i get this
![Auswahl_262](https://user-images.githubusercontent.com/26381449/73484776-33bcde00-43a2-11ea-83ef-25ff78da70b5.png)

which shows `type: default`, but in the config there's nothing about `default`.
```
          - type: entities
            title: E3/DC
            show_header_toggle: false
            entities:
              - entity: switch.e3dc
                name: S10-xxxxxx
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Firmware: [[ sensor.e3dc_firmware.state ]]"
```
So, is this now an issue with card-tools or secondaryinfo-entity-row?
Where should i open an issue?
