### ISSUE TITLE
Script toggle turns off before script has finished executing

### ISSUE THREAD

**Issue by Dullage** [home-assistant/home-assistant-polymer#4722]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using this example script:
```
test:
  sequence:
    - delay:
        seconds: 10
    - service: light.toggle
      entity_id: light.dining_room_lamp
```
And this lovelace configuration:
```
- type: entities
  title: Test
  entities:
    - script.test
```
I correctly get a toggle switch in the UI (as there is a delay in the script):
![image](https://user-images.githubusercontent.com/16575268/73593978-82cd5500-4501-11ea-9d9d-63851177ee94.png)

However, when toggling the script to the 'on' position, the toggle switch returns to the 'off' positions before the 10 seconds has finished and the light toggled (after about 2 seconds).

## Expected behavior

I expect the toggle switch to remain in the on position for as long as the script is running allowing me to cancel if needed.

## Steps to reproduce

As above.

## Environment

- Home Assistant release with the issue: 0.104.3
- Last working Home Assistant release (if known): Unknown
- UI Type (States or Lovelace): Lovelace (YAML Config)
- Browser and browser version: Chrome 79.0.3945.130
- Operating system: Client = Windows, Home Assistant = Raspbian (Official Docker Container)

## Problem-relevant configuration

As above.

## Javascript errors shown in your browser console/inspector

None.

## Additional information
None.
