### ISSUE TITLE
Lovelace entity-button not working in 0.105.0

### ISSUE THREAD

**Issue by bmf7777** [home-assistant/home-assistant-polymer#4773]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

after upgrading from 104.1->105, i'm receiving this error message when i render lovelace ui
```
Unknown type encountered: entity-button.
type: entity-button
entity: script.message_via_alexa
name: Send
tap_action:
  action: call-service
  service: script.turn_on
  service_data:
    entity_id: script.message_via_alexa
```

## Environment

- Home Assistant release with the issue: 105
- Last working Home Assistant release (if known): 104.1
- UI Type (States or Lovelace): lovelace
- Browser and browser version: firefox and chome
- Operating system: 

## Problem-relevant configuration

```
      - type: entities
        title: 'Alexa Message'
        show_header_toggle: false
        entities:
          - type: entity-button
            entity: script.message_via_alexa
            name: Send
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.message_via_alexa
          - entity: input_text.message
            icon: mdi:cellphone-message
          - entity: input_select.room

```

## Javascript errors shown in your browser console/inspector

```txt

```
