### ISSUE TITLE
The UI editor is writing it's own code

### ISSUE THREAD

**Issue by Unpuertomex** [home-assistant/home-assistant-polymer#4781]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:  HA version 0.105.0
- Last working Home Assistant release (if known): 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version:  Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Ubuntu 18.4

## Problem-relevant configuration

```yaml
type: 'custom:mod-card'
style: |

  ha-card {
    background: none;
    box-shadow: none;
  }
  ha-card {
    background: none;
    box-shadow: none;
  }
  ha-card {
    background: none;
    box-shadow: none;
  }
  ha-card {
    background: none;
    box-shadow: none;
  }
  ha-card {
    background: #53a7ea;
  }
card:
  type: vertical-stack
  cards:
    - type: horizontal-stack
      cards:
    3. The UI keeps adding
  ha-card {
    background: none;
    box-shadow: none;
  }
```

## Javascript errors shown in your browser console/inspector

```txt

```
