### ISSUE TITLE
logbook scrolling issue on mobile browsers Safari and Chrome & iOS Home Assistant app

### ISSUE THREAD

**Issue by WilldabeastHA** [home-assistant/home-assistant-polymer#4791]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
When scrolling on the logbook, it stops recognizing the scroll after 1 line. (as if you were to remove your finger from the screen after scrolling 1 line of logbook)  

## Expected behavior

You should be able to scroll multiple lines of the logbook at a time with out it stopping.

## Steps to reproduce
1. Go to the logbook on an iOS mobile device and try and scroll more than 1 line at a time

## Environment
- Home Assistant release with the issue: Home Assistant 0.105.0
- Last working Home Assistant release (if known): Home Assistant 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Safari , Chrome v80.0.3987.88, iOS Home Assistant App v2019.1
- Operating system: iOS v13.3.1
- Frontend version: 20200130.1 - latest
- Device: iPhone Xs

## Problem-relevant configuration

```
  include:
    entities:
      - cover.garage
  exclude:
    domains:
      - automation
      - media_player
      - sensor
    entities:
      - light.kitchen_lights
      - group.main
      - binary_sensor.garagelighttimer
      - binary_sensor.mud_timer
      - binary_sensor.d1_motion
```
