### ISSUE TITLE
Entity Button Card registering 2 clicks on single tap on iOS.

### ISSUE THREAD

**Issue by mig2008pt** [home-assistant/home-assistant-polymer#4802]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Entity Button Card registers 2 clicks when I tap on it. Double tap action seems to work well.
This only happens on iOS, app or browser. Works as intended on MacBook.

## Environment

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Lisbon
version | 0.105.2
virtualenv | true

- Home Assistant release with the issue: 
0.105.1
0.105.2
- Last working Home Assistant release (if known): 
0.104.3
- UI Type (States or Lovelace): 
Lovelace
- Browser and browser version: 
iOS Home Assistant App
iOS Chrome version 80.0.3987.88 
iOS Safari (iOS 13.3.1).
- Operating system: 
iOS 13.3.1

## Problem-relevant configuration
```
              - type: entity-button
                entity: switch.tomada_04
                name: Shield
                icon: mdi:power
                icon_height: 48px
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
```
or
```
              - type: entity-button
                entity: switch.tomada_02
                name: Foco
                icon: mdi:power
                icon_height: 48px
                tap_action:
                  action: call-service
                  service: switch.toggle
                  service_data:
                    entity_id: switch.tomada_02
                double_tap_action:
                  action: more-info
```

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
May be related with issue;
#4419
