### ISSUE TITLE
0.105: state_color does not work with entity-filter card

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/home-assistant-polymer#4807]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Whereas `state_color` works with the `entities` card it does not with `entity-filter`.

## Expected behavior

Screenshot from version 0.103.2:
![Screenshot from 2020-02-08 08-15-42](https://user-images.githubusercontent.com/44732909/74085842-4b9ffc00-4a4b-11ea-8cd2-410776f57a94.png)

Screenshot from version 0.105.1:
![Screenshot from 2020-02-08 08-16-56](https://user-images.githubusercontent.com/44732909/74085917-1516b100-4a4c-11ea-9e16-20dc16111909.png)

## Steps to reproduce

Edit `ui-lovelace.yaml` and add `state_color: true` to an `entity-filter` card. Refresh Lovelace UI.

## Environment

- Home Assistant release with the issue: 0.105.1 (Docker)
- Last working Home Assistant release (if known): 0.103.2
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 72.02
- Operating system: Ubuntu 18.04.3 LTS

## Problem-relevant configuration

```
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.laundry_door
                state: 'off'
            card:
              type: entity-filter
              state_color: true
              entities:
                - binary_sensor.laundry_door_lock
                - lock.laundry_door_lock
              state_filter:
                - "on"
                - locked
                - unlocked
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by homeassistant** [comment]
This issue has been mentioned on **Home Assistant Community**. There might be relevant details there:

https://community.home-assistant.io/t/state-color-not-working-for-entity-filter/169944/2

**Comment by iantrich** [comment]
Please dont screenshot configurations, copy the text to here

**Comment by tdejneka** [comment]
> ... dont screenshot configurations, copy the text to here

Done.

**Comment by iantrich** [comment]
Options for the card should be under a nested `card` option. Check the docs again

**Comment by tdejneka** [comment]
I reduced the code down to this but `state_color` still has no effect.
```
    cards:
      - type: entity-filter
        state_color: true
        entities:
          - binary_sensor.laundry_door_lock
          - lock.laundry_door_lock
        state_filter:
          - "on"
          - locked
          - unlocked
```

Where would your suggested "nested `card` option" go in that example?

**Comment by iantrich** [comment]
It's in the docs
```yaml
type: entity-filter
card:
  state_color: true
```
