### ISSUE TITLE
"visible" yaml key ignored

### ISSUE THREAD

**Issue by Fmstrat** [home-assistant/home-assistant-polymer#4808]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The `visible` key is ignored for views. I'm not sure if this has something to do with a conflict, but here is an example:
```
title: Home
views:
  - badges: []
    cards:
      - entities:
          - entity: light.ge_14295_inwall_smart_toggle_dimmer_level_5
        title: Lights
        type: entities
    path: downstairs
    title: Downstairs
  - badges: []
    cards:
      - entities:
          - entity: switch.basement_lights_switch_3
        title: Lights
        type: entities
    panel: false
    path: basement
    title: Basement
    visible: false
```
Notice the `visible: false`? That tab still shows up. I've also tried:
```
    visible:
      - user: <id>
```
Which is what I really want with no luck.

## Expected behavior
Tab to be hidden based on docs from https://www.home-assistant.io/lovelace/views/

## Steps to reproduce

n/a, use the config above

## Environment

- Home Assistant release with the issue: 0.96.5
- Last working Home Assistant release (if known): n/a
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox (latest)
- Operating system: Ubuntu 18.04

## Problem-relevant configuration
See above

## Javascript errors shown in your browser console/inspector

None

## Additional information
n/a
