### ISSUE TITLE
0.105: state_color change not implemented by entity-button card

### ISSUE THREAD

**Issue by TazUk** [home-assistant/home-assistant-polymer#4815]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): 0.104.3 
- UI Type (States or Lovelace): Frontend version: 20200130.2 - latest
- Browser and browser version: Chrome v79.0.3945.123 and Chrome v80
- Operating system: Chromebook and Android 10

## Problem-relevant configuration

**configuration.yaml**
```
input_boolean: 
   garage_notify:
     name: "Notify Garage"
     icon: mdi:cctv
```

```
type: entity-button
tap_action:
  action: toggle
hold_action:
  action: more-info
show_icon: true
show_name: true
entity: input_boolean.garage_notify
```

## Javascript errors shown in your browser console/inspector

```txt

```
