### ISSUE TITLE
Footer - button action settings are ignored 

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#4818]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Button action settings are ignored when in footer. The documentation is poorly written and unclear whether it's possible at all. However,  in the release notes it says "_Very useful for buttons that activate scenes, for example._", so presumably it is supposed to be possible.

## Expected behavior

Button action config should be consistent with other settings for actions in Lovelace.

## Environment

- Home Assistant release with the issue: 0.105.x
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome mobile
- Operating system: Android

## Problem-relevant configuration

```yaml
entities:
  - light.room_light
  - light.floor_lamp
  - light.tv_ambilight
footer:
  entities:
    - switch.fluxer
    - entity: scene.cinema_time
      tap_action:
        action: call-service
        service: scene.turn_on
        service_data:
          entity_id: scene.cinema_time
  type: buttons
title: Lounge room
type: entities
```

## Javascript errors shown in your browser console/inspector

```txt

```
