### ISSUE TITLE
Bug. Thermostat card does not show zero temperature.

### ISSUE THREAD

**Issue by bessarabov** [home-assistant/home-assistant-polymer#4831]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Here is the problem. Thermostat card shows temperature in most cases, but when the temerature is zero (0.0) thermostat card does not show that zero temperature.

Here is an animated gif that shows this bug:

![1](https://user-images.githubusercontent.com/47263/74188920-7f07a400-4c60-11ea-9f9c-b1c42aefdaac.gif)

## Expected behavior

I expect thermostat card to show zero temperature.

## Steps to reproduce

This bug can be reproduces with such `configurations.yaml`

```
default_config:

frontend:

logger:
  default: debug

input_boolean:
  input_boolean:
    initial: off

input_number:
  input_number:
    initial: 18
    min: -10
    max: 40
    step: 0.5

sensor:
  - platform: template
    sensors:
      temperature:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.input_number') | float }}"

script:

switch:
  - platform: template
    switches:
      heater:
        value_template: "{{ is_state('input_boolean.input_boolean', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.input_boolean
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.input_boolean

climate:
  - platform: generic_thermostat
    heater: switch.heater
    target_sensor: sensor.temperature
```

and such ui config:

```
title: Home
views:
  - badges: []
    cards:
      - entities:
          - entity: switch.heater
          - entity: input_number.input_number
            name: temperature
        type: entities
      - entity: climate.generic_thermostat
        type: thermostat
    path: default_view
    title: Home

```

## Environment

- Home Assistant release with the issue: Home Assistant 0.105.1 has this bug 
- Last working Home Assistant release (if known):  I don't know
- UI Type (States or Lovelace):  - lovelace
- Browser and browser version:  Google Chrome 80.0.3987.87 (WebKit 537.36); Safari 13.0 (WebKit 605.1.15)
- Operating system: macOS Mojave 10.14.6

## Problem-relevant configuration

```yaml
```

see the previous section

## Javascript errors shown in your browser console/inspector

```txt
```

none

## Additional information

none
