### ISSUE TITLE
Lovelace state_color for group entities not working

### ISSUE THREAD

**Issue by Amir974** [home-assistant/home-assistant-polymer#4847]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
state_color property not showing groups state color on entities card / glance card and probably others.

![image](https://user-images.githubusercontent.com/4208106/74249092-4a8ff880-4cf1-11ea-90c6-0cb1bc18c041.png)

```
type: glance
card:
  state_color: true
entities:
  - entity: group.ac_automation
  - entity: switch.ac
  - entity: switch.rancilio_coffee_machine
  - entity: input_boolean.speech_notifications
  - entity: group.work_alerts
```

or 

```
type: glance
state_color: true
entities:
  - entity: group.ac_automation
  - entity: switch.ac
  - entity: switch.rancilio_coffee_machine
  - entity: input_boolean.speech_notifications
  - entity: group.work_alerts
```

Same if I use "entities" rather then "glance":
```
type: entities
entities:
  - entity: group.ac_automation
  - entity: switch.ac
  - entity: switch.rancilio_coffee_machine
  - entity: input_boolean.speech_notifications
  - entity: group.work_alerts
state_color: true
```
Input_boolean seems to be effected by state color property, but groups are not...

## Expected behavior

When a group is set to state on - the icon should take yellow color same as other entity types.

## Steps to reproduce

Create a card with "state_color" property set to `true` 
add group entity to entities in card

see the entity icon does not change regardless of group state.

## Environment

- Home Assistant release with the issue: 0.105.3
- Last working Home Assistant release (if known): never
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version: Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Windows 10

## Problem-relevant configuration

```yaml
type: entities
entities:
  - entity: group.ac_automation
  - entity: switch.ac
  - entity: switch.rancilio_coffee_machine
  - entity: input_boolean.speech_notifications
  - entity: group.work_alerts
state_color: true
```

```yaml
type: glance
entities:
  - entity: group.ac_automation
  - entity: switch.ac
  - entity: switch.rancilio_coffee_machine
  - entity: input_boolean.speech_notifications
  - entity: group.work_alerts
state_color: true
```

## Javascript errors shown in your browser console/inspector

```txt

```
