### ISSUE TITLE
Hassio is refreshing constantly

### ISSUE THREAD

**Issue by blattmann** [home-assistant/home-assistant-polymer#4894]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

As described already in this [post](https://community.home-assistant.io/t/hassio-refreshing-constantly/157771) by another member - the UI keeps refreshing
I’m running " Home Assistant 0.105.4" on a Raspberry Pi4. I also updated to the latest OS "HassOS 3.10".

This issue prevents me from working with Node-Red as the page is refreshing every more or less 30 seconds. Other views are also permanently refreshed - so it's not related to Node-Red.

## Expected behavior

No auto-refresh.

## Steps to reproduce

Enter Home Assistant. Select anything in the navigation. Open the network-tab of the Chrome dev tools. Clear any previous logs inside the network tab if present. Wait less than a minute - the view will get refreshed and several requests will be visible in the log.

## Environment

- Home Assistant release with the issue: _"Home Assistant 0.105.4" on "HassOS 3.10"_
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): _Lovelace_
- Browser and browser version: _Chrome (latest version) and Firefox (latest version)_
- Operating system: _OSX Catalina_
- Hardware: _Raspberry Pi4_

## Problem-relevant configuration

```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 184
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# MQTT Broker
mqtt:
  broker: !secret mqtt_url
  username: !secret mqtt_username
  password: !secret mqtt_password

# IFTTT
ifttt:
  key: !secret ifttt_api_key

default_config:

# Enable Nabu Casa
cloud:

# Enable Mobile App
mobile_app:

# Enable the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enable tuya app
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 34
  platform: smart_life

# Enable API mode
api:

# Get system health
system_health:

# Enables configuration UI
config:

# Checks for available updates
updater:

recorder:
  purge_keep_days: 2
  purge_interval: 2

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

### Track the sun ###
sun:

### Text to speech ###
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en'

#lovelace:
#  mode: yaml

### get breaking changes ###
breaking_changes:

### Nuki ###
lock:
  - platform: nuki
    host: !secret nuki_host
    token: !secret nuki_token

### Weather ###
weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

### Google calendar ###
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
  track_new_calendar: true

### Include Files ###
automation: !include automations.yaml
camera: !include cameras.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
ios: !include ios.yaml
media_player: !include mediaplayer.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shelly: !include shelly.yaml

### Include Directories ###
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
```

## Javascript errors shown in your browser console/inspector

```txt

```
