### ISSUE TITLE
light domain lighting is not consistent

### ISSUE THREAD

**Issue by pashdown** [home-assistant/home-assistant-polymer#4956]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
In spite of state_color: true being set for this card, the top two lights never light up.  They are Insteon lights instead of deconz lights, but still in the lights domain.

## Expected behavior
The lights should light when lit.

## Steps to reproduce
1. Use community Isy994  v1.0.11 to import Insteon lights.
2. Turn them on
3. Some will light on the card, some will not.

## Environment
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.6
timezone | America/Denver
version | 0.105.2
virtualenv | true

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): Lovelace
- Browser and browser version:  Firefox 73.0 and Safari 13.0.5
- Operating system: Ubuntu 19.10 and macOS 10.15.3

## Problem-relevant configuration

```
      - entities:
          - light.exterior_office_door
          - light.exterior_bottom_door
          - light.porch
          - light.kitchen_patio
          - light.exterior_laundry_door
          - light.garage_east_door
          - switch.landscape_lights
        show_header_toggle: true
        title: Exterior
        type: entities
        state_color: true
```

## Javascript errors shown in your browser console/inspector

```
Type error: state-badge expected number, but type of light.porch.attributes.brightness is string (255) state-badge.ts:94:20
Type error: state-badge expected number, but type of light.kitchen_patio.attributes.brightness is string (255) 2 state-badge.ts:94:20

```

## Additional information

![Screenshot_2020-02-21 Home Assistant](https://user-images.githubusercontent.com/175150/75062020-2b3a5d80-549f-11ea-99b1-b15c8a96ad73.png)
