### ISSUE TITLE
scene editor turns on entities

### ISSUE THREAD

**Issue by workingmanrob** [home-assistant/home-assistant-polymer#4965]
## Checklist

- [ yes ] I have updated to the latest available Home Assistant version.
- [ no ] I have cleared the cache of my browser.
- [ no ] I have tried a different browser to see if it is related to my browser.

## The problem

Editing a scene I previously created to turn on my living room entertainment system turns the projector on.

## Expected behavior

The projector should not be turned on

## Steps to reproduce

    1. Create a scene that uses epson projector device entity in the frontend
    2. Navigate to scene and click edit
    3. Go shopping for a few hours (not a necessary step really...)
    4. Return home to discover your projector was turned on several hours ago.

## Environment

- Home Assistant release with the issue: 105.5
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): States UI has been deprecated... so Lovelace.
- Browser and browser version: Chromium Version 80.0.3987.87
- Operating system: Ubuntu 18.04 LTS

## Problem-relevant configuration

```yaml
  name: Game Time
  entities:
    media_player.thing:
      cmode: Natural
      friendly_name: Thing
      source: HDMI2
      source_list:
      - HDMI1
      - HDMI2
      - PC
      - VIDEO
      - USB
      - LAN
      - WiFi Direct
      state: 'on'
      supported_features: 36345
      volume_level: '0'
    switch.living_room_stereo:
      friendly_name: Living Room Stereo
      icon: mdi:audio-video
      state: 'on'
```

## Javascript errors shown in your browser console/inspector

```txt

```
