### ISSUE TITLE
Footer Buttons not working after Update

### ISSUE THREAD

**Issue by Guilopesss** [home-assistant/home-assistant-polymer#5002]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

After the Update to Home Assistant 0.106.0 (coming from 0.105.0) the footer buttons of the entities card is not working for me anymore. The buttons are shown, but have no effect.

```yaml
footer:
  entities:
    - entity: script.1582373207779
      icon: 'mdi:lightbulb-off'
    - entity: script.bedtime
  type: buttons
```
I have tested with multiple browsers + the android app.

If I just call the script itself, there is no problem

## Steps to reproduce

Add this to an "entities card" `footer:
 ```yaml
footer:
  entities:
    - entity: script.1582373207779
      icon: 'mdi:lightbulb-off'
    - entity: script.bedtime
  type: buttons
```

## Environment

- Home Assistant release with the issue: 0.106.0
- Last working Home Assistant release (if known):  0.105.0
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```
```

## Javascript errors shown in your browser console/inspector

```txt

```
