### ISSUE TITLE
input_boolean visual state not updated when nested in multiple groups

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/home-assistant-polymer#540]
Here is a sample configuration to illustrate the problem:
```
input_boolean:  
  heater_timer_00_00:
    name: Heater timer 00:00
    initial: off
    icon: mdi:fire
  heater_timer_00_15:
    name: Heater timer 00:15
    initial: off
    icon: mdi:fire
  heater_timer_00_30:
    name: Heater timer 00:30
    initial: off
    icon: mdi:fire
  heater_timer_00_45:
    name: Heater timer 00:45
    initial: off
    icon: mdi:fire

group:
  heater_timer_group_0:
    name: Timer group 00:00 - 04:00
    control: hidden
    entities:
     - input_boolean.heater_timer_00_00
     - input_boolean.heater_timer_00_15
     - input_boolean.heater_timer_00_30
     - input_boolean.heater_timer_00_45
  heater_timer_group:
    name: Heater timer
    control: hidden
    entities:
    - group.heater_timer_group_0
  heater:
    name: Gas heater
    view: yes
    icon: mdi:fire
    entities:
      - group.heater_timer_group
```
The configuration is an excerpt from a larger configuration, but enough to reproduce the issue (last tested on HA 0.56.1).

The way it behaves is:
1. User clicks on Timer group 00:00 - 04:00 and it expands
2. User enables first input_boolean switch - everything is rendered correctly
3. User enables the seconds input_boolean switch. It is briefly enabled, but then it is displayed as if it were disabled. The same is valid for any other switch in the group
4. If the user collapses the group (clicks outside) and re-enters the group, the switch state is displayed correctly. Interaction with switches has the same bug.

So - switch state is correct, but the rendering of the switches is not (this can be confirmed by HA logs).
This happened with both Chrome and Firefox (latest versions) and also on mobile (Chrome), so I don't think it's a browser bug.

Let me know if I can provide more details.
