### ISSUE TITLE
Unable to create new automations in editor

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant/home-assistant-polymer#681]
**Home Assistant release (`hass --version`):**
0.59.0.dev0

**Home Assistant frontend version:**
home-assistant-frontend (20171121.1)

**Browser and OS:**
Chrome Version 62.0.3202.94 (Officiell version) (64 bit)
Ubuntu 14.04

**Python release (`python3 --version`):**
Python 3.5.3

**Component/platform:**
Automation editor

**Description of problem:**
I can't add triggers or actions when I'm trying to create a new automation. Saving the automation does not work either of course. Existing automations are editable.
I'm getting this error in the chrome dev console when I'm trying the automation editor on dev branch:
```
Uncaught TypeError: this._updateComponent is not a function
    at Object.configChanged [as onChange] (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:6)
    at te.sequenceChanged (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:4)
    at ne.actionChanged (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:4)
    at V.serviceDataChanged (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:4)
    at W.onChange (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:4)
    at HTMLElement.p (ha-panel-config-be91b63a6a92dab6b57f629ac9a6d691.html:4)
    at s (frontend-8da63447d77e19fa74c4583ce2f1907d.html:1)
    at Object.n [as fn] (frontend-8da63447d77e19fa74c4583ce2f1907d.html:1)
    at a (frontend-8da63447d77e19fa74c4583ce2f1907d.html:1)
    at i (frontend-8da63447d77e19fa74c4583ce2f1907d.html:1)
```
**Expected:**
To be able to add new automations using the automation editor.

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
alarm_control_panel:
  - platform: demo

automation: !include automations.yaml

frontend:
  javascript_version: latest
```
```yaml
# automations.yaml
- id: automation.night_alarm
  alias: Night alarm
  hide_entity: true
  trigger:
  - at: 00:30:00
    platform: time
  action:
  - entity_id:
    - alarm_control_panel.alarm
    service: alarm_control_panel.alarm_arm_night
```

1. Activate the alarm control panel demo platform in the configuration.yaml.
2. Create automations.yaml in your config directory.
3. Add the above automation to automations.yaml.
4. Configure automation component to include automations.yaml.
5. Start hass and try to add a new automation.
6. See error in chrome dev console.

**Traceback (if applicable):**
N/A

**Additional info:**
N/A
