### ISSUE TITLE
local images for icon isn't working

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#73]
I have the following customization:

```yaml
switch.digibox:
  friendly_name: 'Telenet Digibox'
  icon: /local/telenet.png
```

The switch is a template_switch as follows:
```yaml
- platform: template
  switches:
    digibox:
      friendly_name: 'Digibox'
      value_template: '{{ states.binary_sensor.digibox.state }}'
      entity_id: binary_sensor.digibox
      turn_on:
        service: shell_command.telenet_powertoggle
      turn_off:
        service: mqtt.publish
        data:
          topic: "cec/off"
          payload: "3"
```

In my configuration folder, I have folder `www`, with the file `telenet.png`. I get the file correctly when I go to `localhost:8123/local/telenet.png`

In the interface, there is no icon. When I specify `icon: mdi:television` or something like that, it works correctly.
