### ISSUE TITLE
Operation mode influence between different thermostats

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/home-assistant-polymer#767]
Using the below configuration:

```
climate:
  - platform: demo
  - platform: generic_thermostat
    name: Study
    heater: switch.study_heater
    target_sensor: sensor.study_temperature
    cold_tolerance: 0.3
    target_temp: 22
    hot_tolerance: 0.3

switch:
  - platform: template
    switches:
      study_heater:
        value_template: "{{ is_state('input_boolean.study_heater_bool', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.study_heater_bool
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.study_heater_bool
input_boolean:
  study_heater_bool:
```
![screen shot 2017-12-28 at 20 37 54](https://user-images.githubusercontent.com/7738048/34419883-01f69fec-ec0f-11e7-80d5-fc1178a341fd.png)

1. Click on "Study" thermostat
2. Exiting the popup 
3. Clicking on "Hvac" thermostat 

Expected result: 
"cool" displayed in Operation field

Actual result: 
"off" displayed in Operation field (see screenshot)

![screen shot 2017-12-28 at 20 37 02](https://user-images.githubusercontent.com/7738048/34419861-e72b520c-ec0e-11e7-8a38-9d4a5ddf7f84.png)
