### ISSUE TITLE
Clicking top-level group shows items from the first nested group

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/home-assistant-polymer#768]
*Copied from home-assistant/home-assistant#11338*

---

Make sure you are running the latest version of Home Assistant before reporting an issue.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum:

**Home Assistant release (`hass --version`):** 0.60.0

**Python release (`python3 --version`):** Python 3.6.3

**Component/platform:** Group

**Description of problem:** Clicking the header of a group which contains another group opens a dialog containing all of the children from the first child group, as well as the first child group itself and all other child groups.

**Expected:** Only the immediate children of the group clicked would be visible.

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
frontend:

group:
  default_view:
    name: Default View
    view: true
    entities:
      - group.parent
  parent:
    name: Parent
    entities:
      - group.child_1
      - group.child_2
  child_1:
    name: Child 1
    entities:
      - input_boolean.switch_1
      - input_boolean.switch_2
  child_2:
    name: Child 2
    entities:
      - input_boolean.switch_3
      - input_boolean.switch_4

homeassistant:
  name: Example HASS

http:

input_boolean:
  switch_1:
    name: "Switch #1"
  switch_2:
    name: "Switch #2"
  switch_3:
    name: "Switch #3"
  switch_4:
    name: "Switch #4"
```

1. Click "Parent" heading
2. Observe that "Switch <span>#</span>1" and "Switch <span>#</span>2" are visible in the list

**Additional info:**

After some investigation, it looks like it's something to do with the `more-info-dialog` Polymer component, although I don't have enough of an understanding of Polymer to investigate it further.

Quote from @tschmidty69 in home-assistant/home-assistant#11338;

> Switch 1 and Switch 2 are part of the groupedControlDetails which, to be honest, I don't particularly understand why they are displayed this way. It basically picks the first element/group and shows the details for that for the card.

**Screenshot of the issue;**

![parent](https://user-images.githubusercontent.com/1843197/34398943-dbef123c-eb7a-11e7-87ba-65a838037322.png)
