### ISSUE TITLE
Customization settings showing on UI

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/home-assistant-polymer#827]
It looks like customization settings are being shown on the UI for some reason. In this case it is the `emulated_hue_hidden` setting which is pulling through (although I've also seen it with `homebridge_visible`).

Using commit `9c2f6e591d0a646c1871835a1bbe946330aae85f` on `master` (also tried normal Home Assistant 0.61.1). This issue is most likely in a similar vein to #768.

#### Configuration
```YAML
frontend:

emulated_hue:

group:
  default_view:
    name: Default View
    view: true
    entities:
      - group.parent
  parent:
    name: Parent
    entities:
      - group.child_1
      - group.child_2
  child_1:
    name: Child 1
    entities:
      - input_boolean.switch_1
      - input_boolean.switch_2
  child_2:
    name: Child 2
    entities:
      - input_boolean.switch_3
      - input_boolean.switch_4

homeassistant:
  name: Example HASS
  customize:
    input_boolean.switch_1:
      emulated_hue_hidden: false
    input_boolean.switch_2:
      emulated_hue_hidden: false
    input_boolean.switch_3:
      emulated_hue_hidden: false
    input_boolean.switch_4:
      emulated_hue_hidden: false

http:

input_boolean:
  switch_1:
    name: "Switch #1"
  switch_2:
    name: "Switch #2"
  switch_3:
    name: "Switch #3"
  switch_4:
    name: "Switch #4"
```

#### Screenshots

<img width="407" alt="Child #1" src="https://user-images.githubusercontent.com/1843197/35202079-452cbfdc-ff18-11e7-9031-9f760f921946.png">
<img width="415" alt="Child #2" src="https://user-images.githubusercontent.com/1843197/35202078-451324aa-ff18-11e7-8fe7-7852cd3c9e36.png">
